/* soapServer.c
   Generated by gSOAP 2.8.17 from /home/peng/wg32_dev/my_tools/app/simemusvr.32/mcuhdl/gsoap/gsm_mcu_hdl.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.17 2017-09-25 07:39:49 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsm-simcard-enable"))
		return soap_serve_ns__gsm_simcard_enable(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsm-simcard-disable"))
		return soap_serve_ns__gsm_simcard_disable(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsm-get-simcard-status"))
		return soap_serve_ns__gsm_get_simcard_status(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsm-module-power-on"))
		return soap_serve_ns__gsm_module_power_on(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsm-module-power-off"))
		return soap_serve_ns__gsm_module_power_off(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsm-get-module-power-status"))
		return soap_serve_ns__gsm_get_module_power_status(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsm-module-emerg-off"))
		return soap_serve_ns__gsm_module_emerg_off(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsm-module-on"))
		return soap_serve_ns__gsm_module_on(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsm-module-off"))
		return soap_serve_ns__gsm_module_off(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsm-get-module-status"))
		return soap_serve_ns__gsm_get_module_status(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsm-get-simcard-insert-status"))
		return soap_serve_ns__gsm_get_simcard_insert_status(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsm-get-gsmboard-insert-status"))
		return soap_serve_ns__gsm_get_gsmboard_insert_status(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsm-set-led-control"))
		return soap_serve_ns__gsm_set_led_control(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsm-get-mcu-version"))
		return soap_serve_ns__gsm_get_mcu_version(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsm-get-mcu-help"))
		return soap_serve_ns__gsm_get_mcu_help(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsm-get-restore-event"))
		return soap_serve_ns__gsm_get_restore_event(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsm-mcu-reg-read"))
		return soap_serve_ns__gsm_mcu_reg_read(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsm-mcu-reg-write"))
		return soap_serve_ns__gsm_mcu_reg_write(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsm_simcard_enable(struct soap *soap)
{	struct ns__gsm_simcard_enable soap_tmp_ns__gsm_simcard_enable;
	struct ns__gsm_simcard_enableResponse soap_tmp_ns__gsm_simcard_enableResponse;
	int soap_tmp_int;
	soap_default_ns__gsm_simcard_enableResponse(soap, &soap_tmp_ns__gsm_simcard_enableResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__gsm_simcard_enableResponse.result = &soap_tmp_int;
	soap_default_ns__gsm_simcard_enable(soap, &soap_tmp_ns__gsm_simcard_enable);
	if (!soap_get_ns__gsm_simcard_enable(soap, &soap_tmp_ns__gsm_simcard_enable, "ns:gsm-simcard-enable", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsm_simcard_enable(soap, soap_tmp_ns__gsm_simcard_enable.chn, soap_tmp_ns__gsm_simcard_enableResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsm_simcard_enableResponse(soap, &soap_tmp_ns__gsm_simcard_enableResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsm_simcard_enableResponse(soap, &soap_tmp_ns__gsm_simcard_enableResponse, "ns:gsm-simcard-enableResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsm_simcard_enableResponse(soap, &soap_tmp_ns__gsm_simcard_enableResponse, "ns:gsm-simcard-enableResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsm_simcard_disable(struct soap *soap)
{	struct ns__gsm_simcard_disable soap_tmp_ns__gsm_simcard_disable;
	struct ns__gsm_simcard_disableResponse soap_tmp_ns__gsm_simcard_disableResponse;
	int soap_tmp_int;
	soap_default_ns__gsm_simcard_disableResponse(soap, &soap_tmp_ns__gsm_simcard_disableResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__gsm_simcard_disableResponse.result = &soap_tmp_int;
	soap_default_ns__gsm_simcard_disable(soap, &soap_tmp_ns__gsm_simcard_disable);
	if (!soap_get_ns__gsm_simcard_disable(soap, &soap_tmp_ns__gsm_simcard_disable, "ns:gsm-simcard-disable", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsm_simcard_disable(soap, soap_tmp_ns__gsm_simcard_disable.chn, soap_tmp_ns__gsm_simcard_disableResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsm_simcard_disableResponse(soap, &soap_tmp_ns__gsm_simcard_disableResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsm_simcard_disableResponse(soap, &soap_tmp_ns__gsm_simcard_disableResponse, "ns:gsm-simcard-disableResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsm_simcard_disableResponse(soap, &soap_tmp_ns__gsm_simcard_disableResponse, "ns:gsm-simcard-disableResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsm_get_simcard_status(struct soap *soap)
{	struct ns__gsm_get_simcard_status soap_tmp_ns__gsm_get_simcard_status;
	struct ns__gsm_mcu_rsp_t result;
	soap_default_ns__gsm_mcu_rsp_t(soap, &result);
	soap_default_ns__gsm_get_simcard_status(soap, &soap_tmp_ns__gsm_get_simcard_status);
	if (!soap_get_ns__gsm_get_simcard_status(soap, &soap_tmp_ns__gsm_get_simcard_status, "ns:gsm-get-simcard-status", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsm_get_simcard_status(soap, soap_tmp_ns__gsm_get_simcard_status.chn, &result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsm_mcu_rsp_t(soap, &result);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsm_mcu_rsp_t(soap, &result, "ns:gsm-mcu-rsp-t", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsm_mcu_rsp_t(soap, &result, "ns:gsm-mcu-rsp-t", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsm_module_power_on(struct soap *soap)
{	struct ns__gsm_module_power_on soap_tmp_ns__gsm_module_power_on;
	struct ns__gsm_module_power_onResponse soap_tmp_ns__gsm_module_power_onResponse;
	int soap_tmp_int;
	soap_default_ns__gsm_module_power_onResponse(soap, &soap_tmp_ns__gsm_module_power_onResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__gsm_module_power_onResponse.result = &soap_tmp_int;
	soap_default_ns__gsm_module_power_on(soap, &soap_tmp_ns__gsm_module_power_on);
	if (!soap_get_ns__gsm_module_power_on(soap, &soap_tmp_ns__gsm_module_power_on, "ns:gsm-module-power-on", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsm_module_power_on(soap, soap_tmp_ns__gsm_module_power_on.chn, soap_tmp_ns__gsm_module_power_onResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsm_module_power_onResponse(soap, &soap_tmp_ns__gsm_module_power_onResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsm_module_power_onResponse(soap, &soap_tmp_ns__gsm_module_power_onResponse, "ns:gsm-module-power-onResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsm_module_power_onResponse(soap, &soap_tmp_ns__gsm_module_power_onResponse, "ns:gsm-module-power-onResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsm_module_power_off(struct soap *soap)
{	struct ns__gsm_module_power_off soap_tmp_ns__gsm_module_power_off;
	struct ns__gsm_module_power_offResponse soap_tmp_ns__gsm_module_power_offResponse;
	int soap_tmp_int;
	soap_default_ns__gsm_module_power_offResponse(soap, &soap_tmp_ns__gsm_module_power_offResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__gsm_module_power_offResponse.result = &soap_tmp_int;
	soap_default_ns__gsm_module_power_off(soap, &soap_tmp_ns__gsm_module_power_off);
	if (!soap_get_ns__gsm_module_power_off(soap, &soap_tmp_ns__gsm_module_power_off, "ns:gsm-module-power-off", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsm_module_power_off(soap, soap_tmp_ns__gsm_module_power_off.chn, soap_tmp_ns__gsm_module_power_offResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsm_module_power_offResponse(soap, &soap_tmp_ns__gsm_module_power_offResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsm_module_power_offResponse(soap, &soap_tmp_ns__gsm_module_power_offResponse, "ns:gsm-module-power-offResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsm_module_power_offResponse(soap, &soap_tmp_ns__gsm_module_power_offResponse, "ns:gsm-module-power-offResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsm_get_module_power_status(struct soap *soap)
{	struct ns__gsm_get_module_power_status soap_tmp_ns__gsm_get_module_power_status;
	struct ns__gsm_mcu_rsp_t result;
	soap_default_ns__gsm_mcu_rsp_t(soap, &result);
	soap_default_ns__gsm_get_module_power_status(soap, &soap_tmp_ns__gsm_get_module_power_status);
	if (!soap_get_ns__gsm_get_module_power_status(soap, &soap_tmp_ns__gsm_get_module_power_status, "ns:gsm-get-module-power-status", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsm_get_module_power_status(soap, soap_tmp_ns__gsm_get_module_power_status.chn, &result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsm_mcu_rsp_t(soap, &result);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsm_mcu_rsp_t(soap, &result, "ns:gsm-mcu-rsp-t", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsm_mcu_rsp_t(soap, &result, "ns:gsm-mcu-rsp-t", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsm_module_emerg_off(struct soap *soap)
{	struct ns__gsm_module_emerg_off soap_tmp_ns__gsm_module_emerg_off;
	struct ns__gsm_module_emerg_offResponse soap_tmp_ns__gsm_module_emerg_offResponse;
	int soap_tmp_int;
	soap_default_ns__gsm_module_emerg_offResponse(soap, &soap_tmp_ns__gsm_module_emerg_offResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__gsm_module_emerg_offResponse.result = &soap_tmp_int;
	soap_default_ns__gsm_module_emerg_off(soap, &soap_tmp_ns__gsm_module_emerg_off);
	if (!soap_get_ns__gsm_module_emerg_off(soap, &soap_tmp_ns__gsm_module_emerg_off, "ns:gsm-module-emerg-off", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsm_module_emerg_off(soap, soap_tmp_ns__gsm_module_emerg_off.chn, soap_tmp_ns__gsm_module_emerg_offResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsm_module_emerg_offResponse(soap, &soap_tmp_ns__gsm_module_emerg_offResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsm_module_emerg_offResponse(soap, &soap_tmp_ns__gsm_module_emerg_offResponse, "ns:gsm-module-emerg-offResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsm_module_emerg_offResponse(soap, &soap_tmp_ns__gsm_module_emerg_offResponse, "ns:gsm-module-emerg-offResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsm_module_on(struct soap *soap)
{	struct ns__gsm_module_on soap_tmp_ns__gsm_module_on;
	struct ns__gsm_module_onResponse soap_tmp_ns__gsm_module_onResponse;
	int soap_tmp_int;
	soap_default_ns__gsm_module_onResponse(soap, &soap_tmp_ns__gsm_module_onResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__gsm_module_onResponse.result = &soap_tmp_int;
	soap_default_ns__gsm_module_on(soap, &soap_tmp_ns__gsm_module_on);
	if (!soap_get_ns__gsm_module_on(soap, &soap_tmp_ns__gsm_module_on, "ns:gsm-module-on", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsm_module_on(soap, soap_tmp_ns__gsm_module_on.chn, soap_tmp_ns__gsm_module_onResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsm_module_onResponse(soap, &soap_tmp_ns__gsm_module_onResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsm_module_onResponse(soap, &soap_tmp_ns__gsm_module_onResponse, "ns:gsm-module-onResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsm_module_onResponse(soap, &soap_tmp_ns__gsm_module_onResponse, "ns:gsm-module-onResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsm_module_off(struct soap *soap)
{	struct ns__gsm_module_off soap_tmp_ns__gsm_module_off;
	struct ns__gsm_module_offResponse soap_tmp_ns__gsm_module_offResponse;
	int soap_tmp_int;
	soap_default_ns__gsm_module_offResponse(soap, &soap_tmp_ns__gsm_module_offResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__gsm_module_offResponse.result = &soap_tmp_int;
	soap_default_ns__gsm_module_off(soap, &soap_tmp_ns__gsm_module_off);
	if (!soap_get_ns__gsm_module_off(soap, &soap_tmp_ns__gsm_module_off, "ns:gsm-module-off", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsm_module_off(soap, soap_tmp_ns__gsm_module_off.chn, soap_tmp_ns__gsm_module_offResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsm_module_offResponse(soap, &soap_tmp_ns__gsm_module_offResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsm_module_offResponse(soap, &soap_tmp_ns__gsm_module_offResponse, "ns:gsm-module-offResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsm_module_offResponse(soap, &soap_tmp_ns__gsm_module_offResponse, "ns:gsm-module-offResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsm_get_module_status(struct soap *soap)
{	struct ns__gsm_get_module_status soap_tmp_ns__gsm_get_module_status;
	struct ns__gsm_mcu_rsp_t result;
	soap_default_ns__gsm_mcu_rsp_t(soap, &result);
	soap_default_ns__gsm_get_module_status(soap, &soap_tmp_ns__gsm_get_module_status);
	if (!soap_get_ns__gsm_get_module_status(soap, &soap_tmp_ns__gsm_get_module_status, "ns:gsm-get-module-status", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsm_get_module_status(soap, soap_tmp_ns__gsm_get_module_status.chn, &result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsm_mcu_rsp_t(soap, &result);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsm_mcu_rsp_t(soap, &result, "ns:gsm-mcu-rsp-t", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsm_mcu_rsp_t(soap, &result, "ns:gsm-mcu-rsp-t", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsm_get_simcard_insert_status(struct soap *soap)
{	struct ns__gsm_get_simcard_insert_status soap_tmp_ns__gsm_get_simcard_insert_status;
	struct ns__gsm_mcu_rsp_t result;
	soap_default_ns__gsm_mcu_rsp_t(soap, &result);
	soap_default_ns__gsm_get_simcard_insert_status(soap, &soap_tmp_ns__gsm_get_simcard_insert_status);
	if (!soap_get_ns__gsm_get_simcard_insert_status(soap, &soap_tmp_ns__gsm_get_simcard_insert_status, "ns:gsm-get-simcard-insert-status", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsm_get_simcard_insert_status(soap, soap_tmp_ns__gsm_get_simcard_insert_status.chn, &result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsm_mcu_rsp_t(soap, &result);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsm_mcu_rsp_t(soap, &result, "ns:gsm-mcu-rsp-t", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsm_mcu_rsp_t(soap, &result, "ns:gsm-mcu-rsp-t", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsm_get_gsmboard_insert_status(struct soap *soap)
{	struct ns__gsm_get_gsmboard_insert_status soap_tmp_ns__gsm_get_gsmboard_insert_status;
	struct ns__gsm_mcu_rsp_t result;
	soap_default_ns__gsm_mcu_rsp_t(soap, &result);
	soap_default_ns__gsm_get_gsmboard_insert_status(soap, &soap_tmp_ns__gsm_get_gsmboard_insert_status);
	if (!soap_get_ns__gsm_get_gsmboard_insert_status(soap, &soap_tmp_ns__gsm_get_gsmboard_insert_status, "ns:gsm-get-gsmboard-insert-status", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsm_get_gsmboard_insert_status(soap, soap_tmp_ns__gsm_get_gsmboard_insert_status.chn, &result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsm_mcu_rsp_t(soap, &result);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsm_mcu_rsp_t(soap, &result, "ns:gsm-mcu-rsp-t", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsm_mcu_rsp_t(soap, &result, "ns:gsm-mcu-rsp-t", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsm_set_led_control(struct soap *soap)
{	struct ns__gsm_set_led_control soap_tmp_ns__gsm_set_led_control;
	struct ns__gsm_set_led_controlResponse soap_tmp_ns__gsm_set_led_controlResponse;
	char * soap_tmp_string;
	soap_default_ns__gsm_set_led_controlResponse(soap, &soap_tmp_ns__gsm_set_led_controlResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__gsm_set_led_controlResponse.result = &soap_tmp_string;
	soap_default_ns__gsm_set_led_control(soap, &soap_tmp_ns__gsm_set_led_control);
	if (!soap_get_ns__gsm_set_led_control(soap, &soap_tmp_ns__gsm_set_led_control, "ns:gsm-set-led-control", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsm_set_led_control(soap, soap_tmp_ns__gsm_set_led_control.buf, soap_tmp_ns__gsm_set_led_controlResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsm_set_led_controlResponse(soap, &soap_tmp_ns__gsm_set_led_controlResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsm_set_led_controlResponse(soap, &soap_tmp_ns__gsm_set_led_controlResponse, "ns:gsm-set-led-controlResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsm_set_led_controlResponse(soap, &soap_tmp_ns__gsm_set_led_controlResponse, "ns:gsm-set-led-controlResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsm_get_mcu_version(struct soap *soap)
{	struct ns__gsm_get_mcu_version soap_tmp_ns__gsm_get_mcu_version;
	struct ns__gsm_get_mcu_versionResponse soap_tmp_ns__gsm_get_mcu_versionResponse;
	char * soap_tmp_string;
	soap_default_ns__gsm_get_mcu_versionResponse(soap, &soap_tmp_ns__gsm_get_mcu_versionResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__gsm_get_mcu_versionResponse.result = &soap_tmp_string;
	soap_default_ns__gsm_get_mcu_version(soap, &soap_tmp_ns__gsm_get_mcu_version);
	if (!soap_get_ns__gsm_get_mcu_version(soap, &soap_tmp_ns__gsm_get_mcu_version, "ns:gsm-get-mcu-version", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsm_get_mcu_version(soap, soap_tmp_ns__gsm_get_mcu_versionResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsm_get_mcu_versionResponse(soap, &soap_tmp_ns__gsm_get_mcu_versionResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsm_get_mcu_versionResponse(soap, &soap_tmp_ns__gsm_get_mcu_versionResponse, "ns:gsm-get-mcu-versionResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsm_get_mcu_versionResponse(soap, &soap_tmp_ns__gsm_get_mcu_versionResponse, "ns:gsm-get-mcu-versionResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsm_get_mcu_help(struct soap *soap)
{	struct ns__gsm_get_mcu_help soap_tmp_ns__gsm_get_mcu_help;
	struct ns__gsm_get_mcu_helpResponse soap_tmp_ns__gsm_get_mcu_helpResponse;
	char * soap_tmp_string;
	soap_default_ns__gsm_get_mcu_helpResponse(soap, &soap_tmp_ns__gsm_get_mcu_helpResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__gsm_get_mcu_helpResponse.result = &soap_tmp_string;
	soap_default_ns__gsm_get_mcu_help(soap, &soap_tmp_ns__gsm_get_mcu_help);
	if (!soap_get_ns__gsm_get_mcu_help(soap, &soap_tmp_ns__gsm_get_mcu_help, "ns:gsm-get-mcu-help", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsm_get_mcu_help(soap, soap_tmp_ns__gsm_get_mcu_helpResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsm_get_mcu_helpResponse(soap, &soap_tmp_ns__gsm_get_mcu_helpResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsm_get_mcu_helpResponse(soap, &soap_tmp_ns__gsm_get_mcu_helpResponse, "ns:gsm-get-mcu-helpResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsm_get_mcu_helpResponse(soap, &soap_tmp_ns__gsm_get_mcu_helpResponse, "ns:gsm-get-mcu-helpResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsm_get_restore_event(struct soap *soap)
{	struct ns__gsm_get_restore_event soap_tmp_ns__gsm_get_restore_event;
	struct ns__gsm_get_restore_eventResponse soap_tmp_ns__gsm_get_restore_eventResponse;
	char * soap_tmp_string;
	soap_default_ns__gsm_get_restore_eventResponse(soap, &soap_tmp_ns__gsm_get_restore_eventResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__gsm_get_restore_eventResponse.result = &soap_tmp_string;
	soap_default_ns__gsm_get_restore_event(soap, &soap_tmp_ns__gsm_get_restore_event);
	if (!soap_get_ns__gsm_get_restore_event(soap, &soap_tmp_ns__gsm_get_restore_event, "ns:gsm-get-restore-event", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsm_get_restore_event(soap, soap_tmp_ns__gsm_get_restore_eventResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsm_get_restore_eventResponse(soap, &soap_tmp_ns__gsm_get_restore_eventResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsm_get_restore_eventResponse(soap, &soap_tmp_ns__gsm_get_restore_eventResponse, "ns:gsm-get-restore-eventResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsm_get_restore_eventResponse(soap, &soap_tmp_ns__gsm_get_restore_eventResponse, "ns:gsm-get-restore-eventResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsm_mcu_reg_read(struct soap *soap)
{	struct ns__gsm_mcu_reg_read soap_tmp_ns__gsm_mcu_reg_read;
	struct ns__gsm_mcu_reg_readResponse soap_tmp_ns__gsm_mcu_reg_readResponse;
	char * soap_tmp_string;
	soap_default_ns__gsm_mcu_reg_readResponse(soap, &soap_tmp_ns__gsm_mcu_reg_readResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__gsm_mcu_reg_readResponse.result = &soap_tmp_string;
	soap_default_ns__gsm_mcu_reg_read(soap, &soap_tmp_ns__gsm_mcu_reg_read);
	if (!soap_get_ns__gsm_mcu_reg_read(soap, &soap_tmp_ns__gsm_mcu_reg_read, "ns:gsm-mcu-reg-read", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsm_mcu_reg_read(soap, soap_tmp_ns__gsm_mcu_reg_read.brd, soap_tmp_ns__gsm_mcu_reg_read.reg, soap_tmp_ns__gsm_mcu_reg_read.num, soap_tmp_ns__gsm_mcu_reg_readResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsm_mcu_reg_readResponse(soap, &soap_tmp_ns__gsm_mcu_reg_readResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsm_mcu_reg_readResponse(soap, &soap_tmp_ns__gsm_mcu_reg_readResponse, "ns:gsm-mcu-reg-readResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsm_mcu_reg_readResponse(soap, &soap_tmp_ns__gsm_mcu_reg_readResponse, "ns:gsm-mcu-reg-readResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsm_mcu_reg_write(struct soap *soap)
{	struct ns__gsm_mcu_reg_write soap_tmp_ns__gsm_mcu_reg_write;
	struct ns__gsm_mcu_reg_writeResponse soap_tmp_ns__gsm_mcu_reg_writeResponse;
	char * soap_tmp_string;
	soap_default_ns__gsm_mcu_reg_writeResponse(soap, &soap_tmp_ns__gsm_mcu_reg_writeResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__gsm_mcu_reg_writeResponse.result = &soap_tmp_string;
	soap_default_ns__gsm_mcu_reg_write(soap, &soap_tmp_ns__gsm_mcu_reg_write);
	if (!soap_get_ns__gsm_mcu_reg_write(soap, &soap_tmp_ns__gsm_mcu_reg_write, "ns:gsm-mcu-reg-write", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsm_mcu_reg_write(soap, soap_tmp_ns__gsm_mcu_reg_write.brd, soap_tmp_ns__gsm_mcu_reg_write.reg, soap_tmp_ns__gsm_mcu_reg_write.val, soap_tmp_ns__gsm_mcu_reg_writeResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsm_mcu_reg_writeResponse(soap, &soap_tmp_ns__gsm_mcu_reg_writeResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsm_mcu_reg_writeResponse(soap, &soap_tmp_ns__gsm_mcu_reg_writeResponse, "ns:gsm-mcu-reg-writeResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsm_mcu_reg_writeResponse(soap, &soap_tmp_ns__gsm_mcu_reg_writeResponse, "ns:gsm-mcu-reg-writeResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
