/* soapH.h
   Generated by gSOAP 2.8.17 from /home/peng/wg32_dev/my_tools/app/simemusvr.32/mcuhdl/gsoap/gsm_mcu_hdl.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_byte(soap, data),0) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_int(soap, data),0) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);

#ifndef soap_write_unsignedByte
#define soap_write_unsignedByte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_unsignedByte(soap, data),0) || soap_put_unsignedByte(soap, data, "unsignedByte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);

#ifndef soap_read_unsignedByte
#define soap_read_unsignedByte(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedByte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);

#ifndef soap_write_unsignedInt
#define soap_write_unsignedInt(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_unsignedInt(soap, data),0) || soap_put_unsignedInt(soap, data, "unsignedInt", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);

#ifndef soap_read_unsignedInt
#define soap_read_unsignedInt(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedInt(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data),0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data),0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data),0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data),0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data),0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE_ns__gsm_mcu_reg_write
#define SOAP_TYPE_ns__gsm_mcu_reg_write (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_mcu_reg_write(struct soap*, struct ns__gsm_mcu_reg_write *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_mcu_reg_write(struct soap*, const struct ns__gsm_mcu_reg_write *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_mcu_reg_write(struct soap*, const char*, int, const struct ns__gsm_mcu_reg_write *, const char*);
SOAP_FMAC3 struct ns__gsm_mcu_reg_write * SOAP_FMAC4 soap_in_ns__gsm_mcu_reg_write(struct soap*, const char*, struct ns__gsm_mcu_reg_write *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_mcu_reg_write(struct soap*, const struct ns__gsm_mcu_reg_write *, const char*, const char*);

#ifndef soap_write_ns__gsm_mcu_reg_write
#define soap_write_ns__gsm_mcu_reg_write(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_mcu_reg_write(soap, data),0) || soap_put_ns__gsm_mcu_reg_write(soap, data, "ns:gsm-mcu-reg-write", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_mcu_reg_write * SOAP_FMAC4 soap_get_ns__gsm_mcu_reg_write(struct soap*, struct ns__gsm_mcu_reg_write *, const char*, const char*);

#ifndef soap_read_ns__gsm_mcu_reg_write
#define soap_read_ns__gsm_mcu_reg_write(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_mcu_reg_write(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_mcu_reg_writeResponse
#define SOAP_TYPE_ns__gsm_mcu_reg_writeResponse (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_mcu_reg_writeResponse(struct soap*, struct ns__gsm_mcu_reg_writeResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_mcu_reg_writeResponse(struct soap*, const struct ns__gsm_mcu_reg_writeResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_mcu_reg_writeResponse(struct soap*, const char*, int, const struct ns__gsm_mcu_reg_writeResponse *, const char*);
SOAP_FMAC3 struct ns__gsm_mcu_reg_writeResponse * SOAP_FMAC4 soap_in_ns__gsm_mcu_reg_writeResponse(struct soap*, const char*, struct ns__gsm_mcu_reg_writeResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_mcu_reg_writeResponse(struct soap*, const struct ns__gsm_mcu_reg_writeResponse *, const char*, const char*);

#ifndef soap_write_ns__gsm_mcu_reg_writeResponse
#define soap_write_ns__gsm_mcu_reg_writeResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_mcu_reg_writeResponse(soap, data),0) || soap_put_ns__gsm_mcu_reg_writeResponse(soap, data, "ns:gsm-mcu-reg-writeResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_mcu_reg_writeResponse * SOAP_FMAC4 soap_get_ns__gsm_mcu_reg_writeResponse(struct soap*, struct ns__gsm_mcu_reg_writeResponse *, const char*, const char*);

#ifndef soap_read_ns__gsm_mcu_reg_writeResponse
#define soap_read_ns__gsm_mcu_reg_writeResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_mcu_reg_writeResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_mcu_reg_read
#define SOAP_TYPE_ns__gsm_mcu_reg_read (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_mcu_reg_read(struct soap*, struct ns__gsm_mcu_reg_read *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_mcu_reg_read(struct soap*, const struct ns__gsm_mcu_reg_read *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_mcu_reg_read(struct soap*, const char*, int, const struct ns__gsm_mcu_reg_read *, const char*);
SOAP_FMAC3 struct ns__gsm_mcu_reg_read * SOAP_FMAC4 soap_in_ns__gsm_mcu_reg_read(struct soap*, const char*, struct ns__gsm_mcu_reg_read *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_mcu_reg_read(struct soap*, const struct ns__gsm_mcu_reg_read *, const char*, const char*);

#ifndef soap_write_ns__gsm_mcu_reg_read
#define soap_write_ns__gsm_mcu_reg_read(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_mcu_reg_read(soap, data),0) || soap_put_ns__gsm_mcu_reg_read(soap, data, "ns:gsm-mcu-reg-read", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_mcu_reg_read * SOAP_FMAC4 soap_get_ns__gsm_mcu_reg_read(struct soap*, struct ns__gsm_mcu_reg_read *, const char*, const char*);

#ifndef soap_read_ns__gsm_mcu_reg_read
#define soap_read_ns__gsm_mcu_reg_read(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_mcu_reg_read(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_mcu_reg_readResponse
#define SOAP_TYPE_ns__gsm_mcu_reg_readResponse (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_mcu_reg_readResponse(struct soap*, struct ns__gsm_mcu_reg_readResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_mcu_reg_readResponse(struct soap*, const struct ns__gsm_mcu_reg_readResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_mcu_reg_readResponse(struct soap*, const char*, int, const struct ns__gsm_mcu_reg_readResponse *, const char*);
SOAP_FMAC3 struct ns__gsm_mcu_reg_readResponse * SOAP_FMAC4 soap_in_ns__gsm_mcu_reg_readResponse(struct soap*, const char*, struct ns__gsm_mcu_reg_readResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_mcu_reg_readResponse(struct soap*, const struct ns__gsm_mcu_reg_readResponse *, const char*, const char*);

#ifndef soap_write_ns__gsm_mcu_reg_readResponse
#define soap_write_ns__gsm_mcu_reg_readResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_mcu_reg_readResponse(soap, data),0) || soap_put_ns__gsm_mcu_reg_readResponse(soap, data, "ns:gsm-mcu-reg-readResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_mcu_reg_readResponse * SOAP_FMAC4 soap_get_ns__gsm_mcu_reg_readResponse(struct soap*, struct ns__gsm_mcu_reg_readResponse *, const char*, const char*);

#ifndef soap_read_ns__gsm_mcu_reg_readResponse
#define soap_read_ns__gsm_mcu_reg_readResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_mcu_reg_readResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_get_restore_event
#define SOAP_TYPE_ns__gsm_get_restore_event (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_get_restore_event(struct soap*, struct ns__gsm_get_restore_event *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_get_restore_event(struct soap*, const struct ns__gsm_get_restore_event *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_get_restore_event(struct soap*, const char*, int, const struct ns__gsm_get_restore_event *, const char*);
SOAP_FMAC3 struct ns__gsm_get_restore_event * SOAP_FMAC4 soap_in_ns__gsm_get_restore_event(struct soap*, const char*, struct ns__gsm_get_restore_event *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_get_restore_event(struct soap*, const struct ns__gsm_get_restore_event *, const char*, const char*);

#ifndef soap_write_ns__gsm_get_restore_event
#define soap_write_ns__gsm_get_restore_event(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_get_restore_event(soap, data),0) || soap_put_ns__gsm_get_restore_event(soap, data, "ns:gsm-get-restore-event", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_get_restore_event * SOAP_FMAC4 soap_get_ns__gsm_get_restore_event(struct soap*, struct ns__gsm_get_restore_event *, const char*, const char*);

#ifndef soap_read_ns__gsm_get_restore_event
#define soap_read_ns__gsm_get_restore_event(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_get_restore_event(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_get_restore_eventResponse
#define SOAP_TYPE_ns__gsm_get_restore_eventResponse (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_get_restore_eventResponse(struct soap*, struct ns__gsm_get_restore_eventResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_get_restore_eventResponse(struct soap*, const struct ns__gsm_get_restore_eventResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_get_restore_eventResponse(struct soap*, const char*, int, const struct ns__gsm_get_restore_eventResponse *, const char*);
SOAP_FMAC3 struct ns__gsm_get_restore_eventResponse * SOAP_FMAC4 soap_in_ns__gsm_get_restore_eventResponse(struct soap*, const char*, struct ns__gsm_get_restore_eventResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_get_restore_eventResponse(struct soap*, const struct ns__gsm_get_restore_eventResponse *, const char*, const char*);

#ifndef soap_write_ns__gsm_get_restore_eventResponse
#define soap_write_ns__gsm_get_restore_eventResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_get_restore_eventResponse(soap, data),0) || soap_put_ns__gsm_get_restore_eventResponse(soap, data, "ns:gsm-get-restore-eventResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_get_restore_eventResponse * SOAP_FMAC4 soap_get_ns__gsm_get_restore_eventResponse(struct soap*, struct ns__gsm_get_restore_eventResponse *, const char*, const char*);

#ifndef soap_read_ns__gsm_get_restore_eventResponse
#define soap_read_ns__gsm_get_restore_eventResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_get_restore_eventResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_get_mcu_help
#define SOAP_TYPE_ns__gsm_get_mcu_help (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_get_mcu_help(struct soap*, struct ns__gsm_get_mcu_help *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_get_mcu_help(struct soap*, const struct ns__gsm_get_mcu_help *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_get_mcu_help(struct soap*, const char*, int, const struct ns__gsm_get_mcu_help *, const char*);
SOAP_FMAC3 struct ns__gsm_get_mcu_help * SOAP_FMAC4 soap_in_ns__gsm_get_mcu_help(struct soap*, const char*, struct ns__gsm_get_mcu_help *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_get_mcu_help(struct soap*, const struct ns__gsm_get_mcu_help *, const char*, const char*);

#ifndef soap_write_ns__gsm_get_mcu_help
#define soap_write_ns__gsm_get_mcu_help(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_get_mcu_help(soap, data),0) || soap_put_ns__gsm_get_mcu_help(soap, data, "ns:gsm-get-mcu-help", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_get_mcu_help * SOAP_FMAC4 soap_get_ns__gsm_get_mcu_help(struct soap*, struct ns__gsm_get_mcu_help *, const char*, const char*);

#ifndef soap_read_ns__gsm_get_mcu_help
#define soap_read_ns__gsm_get_mcu_help(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_get_mcu_help(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_get_mcu_helpResponse
#define SOAP_TYPE_ns__gsm_get_mcu_helpResponse (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_get_mcu_helpResponse(struct soap*, struct ns__gsm_get_mcu_helpResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_get_mcu_helpResponse(struct soap*, const struct ns__gsm_get_mcu_helpResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_get_mcu_helpResponse(struct soap*, const char*, int, const struct ns__gsm_get_mcu_helpResponse *, const char*);
SOAP_FMAC3 struct ns__gsm_get_mcu_helpResponse * SOAP_FMAC4 soap_in_ns__gsm_get_mcu_helpResponse(struct soap*, const char*, struct ns__gsm_get_mcu_helpResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_get_mcu_helpResponse(struct soap*, const struct ns__gsm_get_mcu_helpResponse *, const char*, const char*);

#ifndef soap_write_ns__gsm_get_mcu_helpResponse
#define soap_write_ns__gsm_get_mcu_helpResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_get_mcu_helpResponse(soap, data),0) || soap_put_ns__gsm_get_mcu_helpResponse(soap, data, "ns:gsm-get-mcu-helpResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_get_mcu_helpResponse * SOAP_FMAC4 soap_get_ns__gsm_get_mcu_helpResponse(struct soap*, struct ns__gsm_get_mcu_helpResponse *, const char*, const char*);

#ifndef soap_read_ns__gsm_get_mcu_helpResponse
#define soap_read_ns__gsm_get_mcu_helpResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_get_mcu_helpResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_get_mcu_version
#define SOAP_TYPE_ns__gsm_get_mcu_version (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_get_mcu_version(struct soap*, struct ns__gsm_get_mcu_version *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_get_mcu_version(struct soap*, const struct ns__gsm_get_mcu_version *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_get_mcu_version(struct soap*, const char*, int, const struct ns__gsm_get_mcu_version *, const char*);
SOAP_FMAC3 struct ns__gsm_get_mcu_version * SOAP_FMAC4 soap_in_ns__gsm_get_mcu_version(struct soap*, const char*, struct ns__gsm_get_mcu_version *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_get_mcu_version(struct soap*, const struct ns__gsm_get_mcu_version *, const char*, const char*);

#ifndef soap_write_ns__gsm_get_mcu_version
#define soap_write_ns__gsm_get_mcu_version(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_get_mcu_version(soap, data),0) || soap_put_ns__gsm_get_mcu_version(soap, data, "ns:gsm-get-mcu-version", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_get_mcu_version * SOAP_FMAC4 soap_get_ns__gsm_get_mcu_version(struct soap*, struct ns__gsm_get_mcu_version *, const char*, const char*);

#ifndef soap_read_ns__gsm_get_mcu_version
#define soap_read_ns__gsm_get_mcu_version(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_get_mcu_version(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_get_mcu_versionResponse
#define SOAP_TYPE_ns__gsm_get_mcu_versionResponse (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_get_mcu_versionResponse(struct soap*, struct ns__gsm_get_mcu_versionResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_get_mcu_versionResponse(struct soap*, const struct ns__gsm_get_mcu_versionResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_get_mcu_versionResponse(struct soap*, const char*, int, const struct ns__gsm_get_mcu_versionResponse *, const char*);
SOAP_FMAC3 struct ns__gsm_get_mcu_versionResponse * SOAP_FMAC4 soap_in_ns__gsm_get_mcu_versionResponse(struct soap*, const char*, struct ns__gsm_get_mcu_versionResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_get_mcu_versionResponse(struct soap*, const struct ns__gsm_get_mcu_versionResponse *, const char*, const char*);

#ifndef soap_write_ns__gsm_get_mcu_versionResponse
#define soap_write_ns__gsm_get_mcu_versionResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_get_mcu_versionResponse(soap, data),0) || soap_put_ns__gsm_get_mcu_versionResponse(soap, data, "ns:gsm-get-mcu-versionResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_get_mcu_versionResponse * SOAP_FMAC4 soap_get_ns__gsm_get_mcu_versionResponse(struct soap*, struct ns__gsm_get_mcu_versionResponse *, const char*, const char*);

#ifndef soap_read_ns__gsm_get_mcu_versionResponse
#define soap_read_ns__gsm_get_mcu_versionResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_get_mcu_versionResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_set_led_control
#define SOAP_TYPE_ns__gsm_set_led_control (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_set_led_control(struct soap*, struct ns__gsm_set_led_control *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_set_led_control(struct soap*, const struct ns__gsm_set_led_control *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_set_led_control(struct soap*, const char*, int, const struct ns__gsm_set_led_control *, const char*);
SOAP_FMAC3 struct ns__gsm_set_led_control * SOAP_FMAC4 soap_in_ns__gsm_set_led_control(struct soap*, const char*, struct ns__gsm_set_led_control *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_set_led_control(struct soap*, const struct ns__gsm_set_led_control *, const char*, const char*);

#ifndef soap_write_ns__gsm_set_led_control
#define soap_write_ns__gsm_set_led_control(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_set_led_control(soap, data),0) || soap_put_ns__gsm_set_led_control(soap, data, "ns:gsm-set-led-control", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_set_led_control * SOAP_FMAC4 soap_get_ns__gsm_set_led_control(struct soap*, struct ns__gsm_set_led_control *, const char*, const char*);

#ifndef soap_read_ns__gsm_set_led_control
#define soap_read_ns__gsm_set_led_control(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_set_led_control(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_set_led_controlResponse
#define SOAP_TYPE_ns__gsm_set_led_controlResponse (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_set_led_controlResponse(struct soap*, struct ns__gsm_set_led_controlResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_set_led_controlResponse(struct soap*, const struct ns__gsm_set_led_controlResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_set_led_controlResponse(struct soap*, const char*, int, const struct ns__gsm_set_led_controlResponse *, const char*);
SOAP_FMAC3 struct ns__gsm_set_led_controlResponse * SOAP_FMAC4 soap_in_ns__gsm_set_led_controlResponse(struct soap*, const char*, struct ns__gsm_set_led_controlResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_set_led_controlResponse(struct soap*, const struct ns__gsm_set_led_controlResponse *, const char*, const char*);

#ifndef soap_write_ns__gsm_set_led_controlResponse
#define soap_write_ns__gsm_set_led_controlResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_set_led_controlResponse(soap, data),0) || soap_put_ns__gsm_set_led_controlResponse(soap, data, "ns:gsm-set-led-controlResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_set_led_controlResponse * SOAP_FMAC4 soap_get_ns__gsm_set_led_controlResponse(struct soap*, struct ns__gsm_set_led_controlResponse *, const char*, const char*);

#ifndef soap_read_ns__gsm_set_led_controlResponse
#define soap_read_ns__gsm_set_led_controlResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_set_led_controlResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_get_gsmboard_insert_status
#define SOAP_TYPE_ns__gsm_get_gsmboard_insert_status (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_get_gsmboard_insert_status(struct soap*, struct ns__gsm_get_gsmboard_insert_status *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_get_gsmboard_insert_status(struct soap*, const struct ns__gsm_get_gsmboard_insert_status *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_get_gsmboard_insert_status(struct soap*, const char*, int, const struct ns__gsm_get_gsmboard_insert_status *, const char*);
SOAP_FMAC3 struct ns__gsm_get_gsmboard_insert_status * SOAP_FMAC4 soap_in_ns__gsm_get_gsmboard_insert_status(struct soap*, const char*, struct ns__gsm_get_gsmboard_insert_status *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_get_gsmboard_insert_status(struct soap*, const struct ns__gsm_get_gsmboard_insert_status *, const char*, const char*);

#ifndef soap_write_ns__gsm_get_gsmboard_insert_status
#define soap_write_ns__gsm_get_gsmboard_insert_status(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_get_gsmboard_insert_status(soap, data),0) || soap_put_ns__gsm_get_gsmboard_insert_status(soap, data, "ns:gsm-get-gsmboard-insert-status", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_get_gsmboard_insert_status * SOAP_FMAC4 soap_get_ns__gsm_get_gsmboard_insert_status(struct soap*, struct ns__gsm_get_gsmboard_insert_status *, const char*, const char*);

#ifndef soap_read_ns__gsm_get_gsmboard_insert_status
#define soap_read_ns__gsm_get_gsmboard_insert_status(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_get_gsmboard_insert_status(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_get_simcard_insert_status
#define SOAP_TYPE_ns__gsm_get_simcard_insert_status (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_get_simcard_insert_status(struct soap*, struct ns__gsm_get_simcard_insert_status *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_get_simcard_insert_status(struct soap*, const struct ns__gsm_get_simcard_insert_status *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_get_simcard_insert_status(struct soap*, const char*, int, const struct ns__gsm_get_simcard_insert_status *, const char*);
SOAP_FMAC3 struct ns__gsm_get_simcard_insert_status * SOAP_FMAC4 soap_in_ns__gsm_get_simcard_insert_status(struct soap*, const char*, struct ns__gsm_get_simcard_insert_status *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_get_simcard_insert_status(struct soap*, const struct ns__gsm_get_simcard_insert_status *, const char*, const char*);

#ifndef soap_write_ns__gsm_get_simcard_insert_status
#define soap_write_ns__gsm_get_simcard_insert_status(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_get_simcard_insert_status(soap, data),0) || soap_put_ns__gsm_get_simcard_insert_status(soap, data, "ns:gsm-get-simcard-insert-status", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_get_simcard_insert_status * SOAP_FMAC4 soap_get_ns__gsm_get_simcard_insert_status(struct soap*, struct ns__gsm_get_simcard_insert_status *, const char*, const char*);

#ifndef soap_read_ns__gsm_get_simcard_insert_status
#define soap_read_ns__gsm_get_simcard_insert_status(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_get_simcard_insert_status(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_get_module_status
#define SOAP_TYPE_ns__gsm_get_module_status (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_get_module_status(struct soap*, struct ns__gsm_get_module_status *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_get_module_status(struct soap*, const struct ns__gsm_get_module_status *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_get_module_status(struct soap*, const char*, int, const struct ns__gsm_get_module_status *, const char*);
SOAP_FMAC3 struct ns__gsm_get_module_status * SOAP_FMAC4 soap_in_ns__gsm_get_module_status(struct soap*, const char*, struct ns__gsm_get_module_status *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_get_module_status(struct soap*, const struct ns__gsm_get_module_status *, const char*, const char*);

#ifndef soap_write_ns__gsm_get_module_status
#define soap_write_ns__gsm_get_module_status(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_get_module_status(soap, data),0) || soap_put_ns__gsm_get_module_status(soap, data, "ns:gsm-get-module-status", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_get_module_status * SOAP_FMAC4 soap_get_ns__gsm_get_module_status(struct soap*, struct ns__gsm_get_module_status *, const char*, const char*);

#ifndef soap_read_ns__gsm_get_module_status
#define soap_read_ns__gsm_get_module_status(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_get_module_status(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_module_off
#define SOAP_TYPE_ns__gsm_module_off (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_module_off(struct soap*, struct ns__gsm_module_off *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_module_off(struct soap*, const struct ns__gsm_module_off *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_module_off(struct soap*, const char*, int, const struct ns__gsm_module_off *, const char*);
SOAP_FMAC3 struct ns__gsm_module_off * SOAP_FMAC4 soap_in_ns__gsm_module_off(struct soap*, const char*, struct ns__gsm_module_off *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_module_off(struct soap*, const struct ns__gsm_module_off *, const char*, const char*);

#ifndef soap_write_ns__gsm_module_off
#define soap_write_ns__gsm_module_off(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_module_off(soap, data),0) || soap_put_ns__gsm_module_off(soap, data, "ns:gsm-module-off", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_module_off * SOAP_FMAC4 soap_get_ns__gsm_module_off(struct soap*, struct ns__gsm_module_off *, const char*, const char*);

#ifndef soap_read_ns__gsm_module_off
#define soap_read_ns__gsm_module_off(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_module_off(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_module_offResponse
#define SOAP_TYPE_ns__gsm_module_offResponse (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_module_offResponse(struct soap*, struct ns__gsm_module_offResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_module_offResponse(struct soap*, const struct ns__gsm_module_offResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_module_offResponse(struct soap*, const char*, int, const struct ns__gsm_module_offResponse *, const char*);
SOAP_FMAC3 struct ns__gsm_module_offResponse * SOAP_FMAC4 soap_in_ns__gsm_module_offResponse(struct soap*, const char*, struct ns__gsm_module_offResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_module_offResponse(struct soap*, const struct ns__gsm_module_offResponse *, const char*, const char*);

#ifndef soap_write_ns__gsm_module_offResponse
#define soap_write_ns__gsm_module_offResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_module_offResponse(soap, data),0) || soap_put_ns__gsm_module_offResponse(soap, data, "ns:gsm-module-offResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_module_offResponse * SOAP_FMAC4 soap_get_ns__gsm_module_offResponse(struct soap*, struct ns__gsm_module_offResponse *, const char*, const char*);

#ifndef soap_read_ns__gsm_module_offResponse
#define soap_read_ns__gsm_module_offResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_module_offResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_module_on
#define SOAP_TYPE_ns__gsm_module_on (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_module_on(struct soap*, struct ns__gsm_module_on *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_module_on(struct soap*, const struct ns__gsm_module_on *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_module_on(struct soap*, const char*, int, const struct ns__gsm_module_on *, const char*);
SOAP_FMAC3 struct ns__gsm_module_on * SOAP_FMAC4 soap_in_ns__gsm_module_on(struct soap*, const char*, struct ns__gsm_module_on *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_module_on(struct soap*, const struct ns__gsm_module_on *, const char*, const char*);

#ifndef soap_write_ns__gsm_module_on
#define soap_write_ns__gsm_module_on(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_module_on(soap, data),0) || soap_put_ns__gsm_module_on(soap, data, "ns:gsm-module-on", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_module_on * SOAP_FMAC4 soap_get_ns__gsm_module_on(struct soap*, struct ns__gsm_module_on *, const char*, const char*);

#ifndef soap_read_ns__gsm_module_on
#define soap_read_ns__gsm_module_on(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_module_on(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_module_onResponse
#define SOAP_TYPE_ns__gsm_module_onResponse (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_module_onResponse(struct soap*, struct ns__gsm_module_onResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_module_onResponse(struct soap*, const struct ns__gsm_module_onResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_module_onResponse(struct soap*, const char*, int, const struct ns__gsm_module_onResponse *, const char*);
SOAP_FMAC3 struct ns__gsm_module_onResponse * SOAP_FMAC4 soap_in_ns__gsm_module_onResponse(struct soap*, const char*, struct ns__gsm_module_onResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_module_onResponse(struct soap*, const struct ns__gsm_module_onResponse *, const char*, const char*);

#ifndef soap_write_ns__gsm_module_onResponse
#define soap_write_ns__gsm_module_onResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_module_onResponse(soap, data),0) || soap_put_ns__gsm_module_onResponse(soap, data, "ns:gsm-module-onResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_module_onResponse * SOAP_FMAC4 soap_get_ns__gsm_module_onResponse(struct soap*, struct ns__gsm_module_onResponse *, const char*, const char*);

#ifndef soap_read_ns__gsm_module_onResponse
#define soap_read_ns__gsm_module_onResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_module_onResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_module_emerg_off
#define SOAP_TYPE_ns__gsm_module_emerg_off (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_module_emerg_off(struct soap*, struct ns__gsm_module_emerg_off *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_module_emerg_off(struct soap*, const struct ns__gsm_module_emerg_off *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_module_emerg_off(struct soap*, const char*, int, const struct ns__gsm_module_emerg_off *, const char*);
SOAP_FMAC3 struct ns__gsm_module_emerg_off * SOAP_FMAC4 soap_in_ns__gsm_module_emerg_off(struct soap*, const char*, struct ns__gsm_module_emerg_off *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_module_emerg_off(struct soap*, const struct ns__gsm_module_emerg_off *, const char*, const char*);

#ifndef soap_write_ns__gsm_module_emerg_off
#define soap_write_ns__gsm_module_emerg_off(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_module_emerg_off(soap, data),0) || soap_put_ns__gsm_module_emerg_off(soap, data, "ns:gsm-module-emerg-off", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_module_emerg_off * SOAP_FMAC4 soap_get_ns__gsm_module_emerg_off(struct soap*, struct ns__gsm_module_emerg_off *, const char*, const char*);

#ifndef soap_read_ns__gsm_module_emerg_off
#define soap_read_ns__gsm_module_emerg_off(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_module_emerg_off(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_module_emerg_offResponse
#define SOAP_TYPE_ns__gsm_module_emerg_offResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_module_emerg_offResponse(struct soap*, struct ns__gsm_module_emerg_offResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_module_emerg_offResponse(struct soap*, const struct ns__gsm_module_emerg_offResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_module_emerg_offResponse(struct soap*, const char*, int, const struct ns__gsm_module_emerg_offResponse *, const char*);
SOAP_FMAC3 struct ns__gsm_module_emerg_offResponse * SOAP_FMAC4 soap_in_ns__gsm_module_emerg_offResponse(struct soap*, const char*, struct ns__gsm_module_emerg_offResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_module_emerg_offResponse(struct soap*, const struct ns__gsm_module_emerg_offResponse *, const char*, const char*);

#ifndef soap_write_ns__gsm_module_emerg_offResponse
#define soap_write_ns__gsm_module_emerg_offResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_module_emerg_offResponse(soap, data),0) || soap_put_ns__gsm_module_emerg_offResponse(soap, data, "ns:gsm-module-emerg-offResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_module_emerg_offResponse * SOAP_FMAC4 soap_get_ns__gsm_module_emerg_offResponse(struct soap*, struct ns__gsm_module_emerg_offResponse *, const char*, const char*);

#ifndef soap_read_ns__gsm_module_emerg_offResponse
#define soap_read_ns__gsm_module_emerg_offResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_module_emerg_offResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_get_module_power_status
#define SOAP_TYPE_ns__gsm_get_module_power_status (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_get_module_power_status(struct soap*, struct ns__gsm_get_module_power_status *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_get_module_power_status(struct soap*, const struct ns__gsm_get_module_power_status *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_get_module_power_status(struct soap*, const char*, int, const struct ns__gsm_get_module_power_status *, const char*);
SOAP_FMAC3 struct ns__gsm_get_module_power_status * SOAP_FMAC4 soap_in_ns__gsm_get_module_power_status(struct soap*, const char*, struct ns__gsm_get_module_power_status *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_get_module_power_status(struct soap*, const struct ns__gsm_get_module_power_status *, const char*, const char*);

#ifndef soap_write_ns__gsm_get_module_power_status
#define soap_write_ns__gsm_get_module_power_status(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_get_module_power_status(soap, data),0) || soap_put_ns__gsm_get_module_power_status(soap, data, "ns:gsm-get-module-power-status", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_get_module_power_status * SOAP_FMAC4 soap_get_ns__gsm_get_module_power_status(struct soap*, struct ns__gsm_get_module_power_status *, const char*, const char*);

#ifndef soap_read_ns__gsm_get_module_power_status
#define soap_read_ns__gsm_get_module_power_status(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_get_module_power_status(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_module_power_off
#define SOAP_TYPE_ns__gsm_module_power_off (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_module_power_off(struct soap*, struct ns__gsm_module_power_off *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_module_power_off(struct soap*, const struct ns__gsm_module_power_off *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_module_power_off(struct soap*, const char*, int, const struct ns__gsm_module_power_off *, const char*);
SOAP_FMAC3 struct ns__gsm_module_power_off * SOAP_FMAC4 soap_in_ns__gsm_module_power_off(struct soap*, const char*, struct ns__gsm_module_power_off *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_module_power_off(struct soap*, const struct ns__gsm_module_power_off *, const char*, const char*);

#ifndef soap_write_ns__gsm_module_power_off
#define soap_write_ns__gsm_module_power_off(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_module_power_off(soap, data),0) || soap_put_ns__gsm_module_power_off(soap, data, "ns:gsm-module-power-off", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_module_power_off * SOAP_FMAC4 soap_get_ns__gsm_module_power_off(struct soap*, struct ns__gsm_module_power_off *, const char*, const char*);

#ifndef soap_read_ns__gsm_module_power_off
#define soap_read_ns__gsm_module_power_off(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_module_power_off(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_module_power_offResponse
#define SOAP_TYPE_ns__gsm_module_power_offResponse (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_module_power_offResponse(struct soap*, struct ns__gsm_module_power_offResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_module_power_offResponse(struct soap*, const struct ns__gsm_module_power_offResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_module_power_offResponse(struct soap*, const char*, int, const struct ns__gsm_module_power_offResponse *, const char*);
SOAP_FMAC3 struct ns__gsm_module_power_offResponse * SOAP_FMAC4 soap_in_ns__gsm_module_power_offResponse(struct soap*, const char*, struct ns__gsm_module_power_offResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_module_power_offResponse(struct soap*, const struct ns__gsm_module_power_offResponse *, const char*, const char*);

#ifndef soap_write_ns__gsm_module_power_offResponse
#define soap_write_ns__gsm_module_power_offResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_module_power_offResponse(soap, data),0) || soap_put_ns__gsm_module_power_offResponse(soap, data, "ns:gsm-module-power-offResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_module_power_offResponse * SOAP_FMAC4 soap_get_ns__gsm_module_power_offResponse(struct soap*, struct ns__gsm_module_power_offResponse *, const char*, const char*);

#ifndef soap_read_ns__gsm_module_power_offResponse
#define soap_read_ns__gsm_module_power_offResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_module_power_offResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_module_power_on
#define SOAP_TYPE_ns__gsm_module_power_on (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_module_power_on(struct soap*, struct ns__gsm_module_power_on *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_module_power_on(struct soap*, const struct ns__gsm_module_power_on *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_module_power_on(struct soap*, const char*, int, const struct ns__gsm_module_power_on *, const char*);
SOAP_FMAC3 struct ns__gsm_module_power_on * SOAP_FMAC4 soap_in_ns__gsm_module_power_on(struct soap*, const char*, struct ns__gsm_module_power_on *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_module_power_on(struct soap*, const struct ns__gsm_module_power_on *, const char*, const char*);

#ifndef soap_write_ns__gsm_module_power_on
#define soap_write_ns__gsm_module_power_on(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_module_power_on(soap, data),0) || soap_put_ns__gsm_module_power_on(soap, data, "ns:gsm-module-power-on", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_module_power_on * SOAP_FMAC4 soap_get_ns__gsm_module_power_on(struct soap*, struct ns__gsm_module_power_on *, const char*, const char*);

#ifndef soap_read_ns__gsm_module_power_on
#define soap_read_ns__gsm_module_power_on(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_module_power_on(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_module_power_onResponse
#define SOAP_TYPE_ns__gsm_module_power_onResponse (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_module_power_onResponse(struct soap*, struct ns__gsm_module_power_onResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_module_power_onResponse(struct soap*, const struct ns__gsm_module_power_onResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_module_power_onResponse(struct soap*, const char*, int, const struct ns__gsm_module_power_onResponse *, const char*);
SOAP_FMAC3 struct ns__gsm_module_power_onResponse * SOAP_FMAC4 soap_in_ns__gsm_module_power_onResponse(struct soap*, const char*, struct ns__gsm_module_power_onResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_module_power_onResponse(struct soap*, const struct ns__gsm_module_power_onResponse *, const char*, const char*);

#ifndef soap_write_ns__gsm_module_power_onResponse
#define soap_write_ns__gsm_module_power_onResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_module_power_onResponse(soap, data),0) || soap_put_ns__gsm_module_power_onResponse(soap, data, "ns:gsm-module-power-onResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_module_power_onResponse * SOAP_FMAC4 soap_get_ns__gsm_module_power_onResponse(struct soap*, struct ns__gsm_module_power_onResponse *, const char*, const char*);

#ifndef soap_read_ns__gsm_module_power_onResponse
#define soap_read_ns__gsm_module_power_onResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_module_power_onResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_get_simcard_status
#define SOAP_TYPE_ns__gsm_get_simcard_status (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_get_simcard_status(struct soap*, struct ns__gsm_get_simcard_status *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_get_simcard_status(struct soap*, const struct ns__gsm_get_simcard_status *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_get_simcard_status(struct soap*, const char*, int, const struct ns__gsm_get_simcard_status *, const char*);
SOAP_FMAC3 struct ns__gsm_get_simcard_status * SOAP_FMAC4 soap_in_ns__gsm_get_simcard_status(struct soap*, const char*, struct ns__gsm_get_simcard_status *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_get_simcard_status(struct soap*, const struct ns__gsm_get_simcard_status *, const char*, const char*);

#ifndef soap_write_ns__gsm_get_simcard_status
#define soap_write_ns__gsm_get_simcard_status(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_get_simcard_status(soap, data),0) || soap_put_ns__gsm_get_simcard_status(soap, data, "ns:gsm-get-simcard-status", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_get_simcard_status * SOAP_FMAC4 soap_get_ns__gsm_get_simcard_status(struct soap*, struct ns__gsm_get_simcard_status *, const char*, const char*);

#ifndef soap_read_ns__gsm_get_simcard_status
#define soap_read_ns__gsm_get_simcard_status(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_get_simcard_status(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_simcard_disable
#define SOAP_TYPE_ns__gsm_simcard_disable (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_simcard_disable(struct soap*, struct ns__gsm_simcard_disable *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_simcard_disable(struct soap*, const struct ns__gsm_simcard_disable *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_simcard_disable(struct soap*, const char*, int, const struct ns__gsm_simcard_disable *, const char*);
SOAP_FMAC3 struct ns__gsm_simcard_disable * SOAP_FMAC4 soap_in_ns__gsm_simcard_disable(struct soap*, const char*, struct ns__gsm_simcard_disable *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_simcard_disable(struct soap*, const struct ns__gsm_simcard_disable *, const char*, const char*);

#ifndef soap_write_ns__gsm_simcard_disable
#define soap_write_ns__gsm_simcard_disable(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_simcard_disable(soap, data),0) || soap_put_ns__gsm_simcard_disable(soap, data, "ns:gsm-simcard-disable", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_simcard_disable * SOAP_FMAC4 soap_get_ns__gsm_simcard_disable(struct soap*, struct ns__gsm_simcard_disable *, const char*, const char*);

#ifndef soap_read_ns__gsm_simcard_disable
#define soap_read_ns__gsm_simcard_disable(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_simcard_disable(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_simcard_disableResponse
#define SOAP_TYPE_ns__gsm_simcard_disableResponse (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_simcard_disableResponse(struct soap*, struct ns__gsm_simcard_disableResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_simcard_disableResponse(struct soap*, const struct ns__gsm_simcard_disableResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_simcard_disableResponse(struct soap*, const char*, int, const struct ns__gsm_simcard_disableResponse *, const char*);
SOAP_FMAC3 struct ns__gsm_simcard_disableResponse * SOAP_FMAC4 soap_in_ns__gsm_simcard_disableResponse(struct soap*, const char*, struct ns__gsm_simcard_disableResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_simcard_disableResponse(struct soap*, const struct ns__gsm_simcard_disableResponse *, const char*, const char*);

#ifndef soap_write_ns__gsm_simcard_disableResponse
#define soap_write_ns__gsm_simcard_disableResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_simcard_disableResponse(soap, data),0) || soap_put_ns__gsm_simcard_disableResponse(soap, data, "ns:gsm-simcard-disableResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_simcard_disableResponse * SOAP_FMAC4 soap_get_ns__gsm_simcard_disableResponse(struct soap*, struct ns__gsm_simcard_disableResponse *, const char*, const char*);

#ifndef soap_read_ns__gsm_simcard_disableResponse
#define soap_read_ns__gsm_simcard_disableResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_simcard_disableResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_simcard_enable
#define SOAP_TYPE_ns__gsm_simcard_enable (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_simcard_enable(struct soap*, struct ns__gsm_simcard_enable *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_simcard_enable(struct soap*, const struct ns__gsm_simcard_enable *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_simcard_enable(struct soap*, const char*, int, const struct ns__gsm_simcard_enable *, const char*);
SOAP_FMAC3 struct ns__gsm_simcard_enable * SOAP_FMAC4 soap_in_ns__gsm_simcard_enable(struct soap*, const char*, struct ns__gsm_simcard_enable *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_simcard_enable(struct soap*, const struct ns__gsm_simcard_enable *, const char*, const char*);

#ifndef soap_write_ns__gsm_simcard_enable
#define soap_write_ns__gsm_simcard_enable(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_simcard_enable(soap, data),0) || soap_put_ns__gsm_simcard_enable(soap, data, "ns:gsm-simcard-enable", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_simcard_enable * SOAP_FMAC4 soap_get_ns__gsm_simcard_enable(struct soap*, struct ns__gsm_simcard_enable *, const char*, const char*);

#ifndef soap_read_ns__gsm_simcard_enable
#define soap_read_ns__gsm_simcard_enable(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_simcard_enable(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_simcard_enableResponse
#define SOAP_TYPE_ns__gsm_simcard_enableResponse (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_simcard_enableResponse(struct soap*, struct ns__gsm_simcard_enableResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_simcard_enableResponse(struct soap*, const struct ns__gsm_simcard_enableResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_simcard_enableResponse(struct soap*, const char*, int, const struct ns__gsm_simcard_enableResponse *, const char*);
SOAP_FMAC3 struct ns__gsm_simcard_enableResponse * SOAP_FMAC4 soap_in_ns__gsm_simcard_enableResponse(struct soap*, const char*, struct ns__gsm_simcard_enableResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_simcard_enableResponse(struct soap*, const struct ns__gsm_simcard_enableResponse *, const char*, const char*);

#ifndef soap_write_ns__gsm_simcard_enableResponse
#define soap_write_ns__gsm_simcard_enableResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_simcard_enableResponse(soap, data),0) || soap_put_ns__gsm_simcard_enableResponse(soap, data, "ns:gsm-simcard-enableResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_simcard_enableResponse * SOAP_FMAC4 soap_get_ns__gsm_simcard_enableResponse(struct soap*, struct ns__gsm_simcard_enableResponse *, const char*, const char*);

#ifndef soap_read_ns__gsm_simcard_enableResponse
#define soap_read_ns__gsm_simcard_enableResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_simcard_enableResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns__gsm_mcu_rsp_t
#define SOAP_TYPE_ns__gsm_mcu_rsp_t (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsm_mcu_rsp_t(struct soap*, struct ns__gsm_mcu_rsp_t *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsm_mcu_rsp_t(struct soap*, const struct ns__gsm_mcu_rsp_t *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsm_mcu_rsp_t(struct soap*, const char*, int, const struct ns__gsm_mcu_rsp_t *, const char*);
SOAP_FMAC3 struct ns__gsm_mcu_rsp_t * SOAP_FMAC4 soap_in_ns__gsm_mcu_rsp_t(struct soap*, const char*, struct ns__gsm_mcu_rsp_t *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsm_mcu_rsp_t(struct soap*, const struct ns__gsm_mcu_rsp_t *, const char*, const char*);

#ifndef soap_write_ns__gsm_mcu_rsp_t
#define soap_write_ns__gsm_mcu_rsp_t(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsm_mcu_rsp_t(soap, data),0) || soap_put_ns__gsm_mcu_rsp_t(soap, data, "ns:gsm-mcu-rsp-t", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_mcu_rsp_t * SOAP_FMAC4 soap_get_ns__gsm_mcu_rsp_t(struct soap*, struct ns__gsm_mcu_rsp_t *, const char*, const char*);

#ifndef soap_read_ns__gsm_mcu_rsp_t
#define soap_read_ns__gsm_mcu_rsp_t(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__gsm_mcu_rsp_t(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data),0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data),0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data),0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap*, const char*, char ***, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap*, char **const*, const char*, const char*);

#ifndef soap_write_PointerTostring
#define soap_write_PointerTostring(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTostring(soap, data),0) || soap_put_PointerTostring(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap*, char ***, const char*, const char*);

#ifndef soap_read_PointerTostring
#define soap_read_PointerTostring(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostring(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons__gsm_mcu_rsp_t
#define SOAP_TYPE_PointerTons__gsm_mcu_rsp_t (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__gsm_mcu_rsp_t(struct soap*, struct ns__gsm_mcu_rsp_t *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__gsm_mcu_rsp_t(struct soap*, const char *, int, struct ns__gsm_mcu_rsp_t *const*, const char *);
SOAP_FMAC3 struct ns__gsm_mcu_rsp_t ** SOAP_FMAC4 soap_in_PointerTons__gsm_mcu_rsp_t(struct soap*, const char*, struct ns__gsm_mcu_rsp_t **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__gsm_mcu_rsp_t(struct soap*, struct ns__gsm_mcu_rsp_t *const*, const char*, const char*);

#ifndef soap_write_PointerTons__gsm_mcu_rsp_t
#define soap_write_PointerTons__gsm_mcu_rsp_t(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons__gsm_mcu_rsp_t(soap, data),0) || soap_put_PointerTons__gsm_mcu_rsp_t(soap, data, "ns:gsm-mcu-rsp-t", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsm_mcu_rsp_t ** SOAP_FMAC4 soap_get_PointerTons__gsm_mcu_rsp_t(struct soap*, struct ns__gsm_mcu_rsp_t **, const char*, const char*);

#ifndef soap_read_PointerTons__gsm_mcu_rsp_t
#define soap_read_PointerTons__gsm_mcu_rsp_t(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons__gsm_mcu_rsp_t(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);

#ifndef soap_write_PointerToint
#define soap_write_PointerToint(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToint(soap, data),0) || soap_put_PointerToint(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);

#ifndef soap_read_PointerToint
#define soap_read_PointerToint(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToint(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__QName(soap, data),0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_string(soap, data),0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
