#!/bin/sh

. /etc/functions.sh

case "$1" in
	start)
		/my_tools/callEventHdl >> /tmp/log/callEventHdl.log &
		;;
	stop)
		killps callEventHdl $$
		;;
	restart)
		$0 stop
		$0 start
		exit 0
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 2
		;;
esac

exit 0
