#!/bin/sh

. /etc/functions.sh

start()
{
	cron > /dev/null 2>&1 &
}

stop()
{
	killps cron $$
}

case "$1" in
	start)
		start
		exit 0
		;;  
	stop)
		stop
		exit 0
		;;  
	restart)
		stop
		start
		exit 0
		;;  
	*)  
		echo "Usage: $0 {start|stop|restart}"
		exit 2
		;;  
esac
