#!/bin/sh

. /etc/functions.sh
start()
{
	if ! ps -ef | grep "/my_tools/logfile_monitor" | grep "/bin/php" > /dev/null 2>&1 ; then
		/my_tools/logfile_monitor > /dev/null 2>&1 &
		/my_tools/keeper "start:logfile_monitor:/etc/init.d/logfile_monitor start"
	fi
	if ! ps -ef | grep "sms_recv" | grep "php" > /dev/null 2>&1 ; then
		/my_tools/lua/sms_receive/sms_recv > /dev/null 2>&1 &
	fi
}

stop()
{
	/my_tools/keeper "stop:logfile_monitor"
	killps logfile_monitor $$
	killps sms_recv $$
}

usage()
{
	echo "Usage: $0 {start|stop|restart|reload}"                              
	exit 2
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		start
		;;
	*)
		usage
		;;
esac
