#!/bin/sh

. /etc/functions.sh

case "$1" in
	start)
		/my_tools/mcuhdlsvr > /dev/null 2>&1 &
		;;
	stop)
		killps mcuhdlsvr $$
		;;
	restart)
		$0 stop
		$0 start
		exit 0
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 2
		;;
esac

exit 0
