/* soapStub.h
   Generated by gSOAP 2.8.36 for soap_gsmio.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/


#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20836
# error "GSOAP VERSION 20836 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Structs and Unions                                                         *
 *                                                                            *
\******************************************************************************/

struct ns__gsmio_rsp_s;	/* soap_gsmio.h:108 */
struct ns__gsmio_set_simcard_srcResponse;	/* soap_gsmio.h:115 */
struct ns__gsmio_set_simcard_src;	/* soap_gsmio.h:115 */
struct ns__gsmio_get_simcard_src;	/* soap_gsmio.h:118 */
struct ns__gsmio_pwr_onResponse;	/* soap_gsmio.h:121 */
struct ns__gsmio_pwr_on;	/* soap_gsmio.h:121 */
struct ns__gsmio_pwr_offResponse;	/* soap_gsmio.h:124 */
struct ns__gsmio_pwr_off;	/* soap_gsmio.h:124 */
struct ns__gsmio_get_pwr_status;	/* soap_gsmio.h:127 */
struct ns__gsmio_pwrkey_onResponse;	/* soap_gsmio.h:130 */
struct ns__gsmio_pwrkey_on;	/* soap_gsmio.h:130 */
struct ns__gsmio_pwrkey_offResponse;	/* soap_gsmio.h:133 */
struct ns__gsmio_pwrkey_off;	/* soap_gsmio.h:133 */
struct ns__gsmio_emerg_offResponse;	/* soap_gsmio.h:136 */
struct ns__gsmio_emerg_off;	/* soap_gsmio.h:136 */
struct ns__gsmio_get_pwrkey_status;	/* soap_gsmio.h:139 */
struct ns__gsmio_get_simcard_insert_status;	/* soap_gsmio.h:142 */
struct ns__gsmio_get_gsmboard_insert_status;	/* soap_gsmio.h:145 */
struct ns__gsmio_get_mcu_versionResponse;	/* soap_gsmio.h:149 */
struct ns__gsmio_get_mcu_version;	/* soap_gsmio.h:149 */
struct ns__gsmio_get_mcu_helpResponse;	/* soap_gsmio.h:153 */
struct ns__gsmio_get_mcu_help;	/* soap_gsmio.h:153 */

/* soap_gsmio.h:108 */
#ifndef SOAP_TYPE_ns__gsmio_rsp_s
#define SOAP_TYPE_ns__gsmio_rsp_s (7)
/* complex XSD type 'ns:gsmio-rsp-s': */
struct ns__gsmio_rsp_s {
        /** Required element 'result' of XSD type 'xsd:int' */
        int result;
        /** Required element 'cnt' of XSD type 'xsd:int' */
        int cnt;
        /** Optional element 'value' of XSD type 'xsd:string' */
        char *value;
};
#endif

/* soap_gsmio.h:115 */
#ifndef SOAP_TYPE_ns__gsmio_set_simcard_srcResponse
#define SOAP_TYPE_ns__gsmio_set_simcard_srcResponse (11)
/* complex XSD type 'ns:gsmio-set-simcard-srcResponse': */
struct ns__gsmio_set_simcard_srcResponse {
        /** Optional element 'result' of XSD type 'xsd:int' */
        int *result;
};
#endif

/* soap_gsmio.h:115 */
#ifndef SOAP_TYPE_ns__gsmio_set_simcard_src
#define SOAP_TYPE_ns__gsmio_set_simcard_src (12)
/* complex XSD type 'ns:gsmio-set-simcard-src': */
struct ns__gsmio_set_simcard_src {
        /** Required element 'chn' of XSD type 'xsd:int' */
        int chn;
        /** Required element 'src' of XSD type 'xsd:int' */
        int src;
};
#endif

/* soap_gsmio.h:118 */
#ifndef SOAP_TYPE_ns__gsmio_get_simcard_src
#define SOAP_TYPE_ns__gsmio_get_simcard_src (15)
/* complex XSD type 'ns:gsmio-get-simcard-src': */
struct ns__gsmio_get_simcard_src {
        /** Required element 'chn' of XSD type 'xsd:int' */
        int chn;
};
#endif

/* soap_gsmio.h:121 */
#ifndef SOAP_TYPE_ns__gsmio_pwr_onResponse
#define SOAP_TYPE_ns__gsmio_pwr_onResponse (17)
/* complex XSD type 'ns:gsmio-pwr-onResponse': */
struct ns__gsmio_pwr_onResponse {
        /** Optional element 'result' of XSD type 'xsd:int' */
        int *result;
};
#endif

/* soap_gsmio.h:121 */
#ifndef SOAP_TYPE_ns__gsmio_pwr_on
#define SOAP_TYPE_ns__gsmio_pwr_on (18)
/* complex XSD type 'ns:gsmio-pwr-on': */
struct ns__gsmio_pwr_on {
        /** Required element 'chn' of XSD type 'xsd:int' */
        int chn;
};
#endif

/* soap_gsmio.h:124 */
#ifndef SOAP_TYPE_ns__gsmio_pwr_offResponse
#define SOAP_TYPE_ns__gsmio_pwr_offResponse (20)
/* complex XSD type 'ns:gsmio-pwr-offResponse': */
struct ns__gsmio_pwr_offResponse {
        /** Optional element 'result' of XSD type 'xsd:int' */
        int *result;
};
#endif

/* soap_gsmio.h:124 */
#ifndef SOAP_TYPE_ns__gsmio_pwr_off
#define SOAP_TYPE_ns__gsmio_pwr_off (21)
/* complex XSD type 'ns:gsmio-pwr-off': */
struct ns__gsmio_pwr_off {
        /** Required element 'chn' of XSD type 'xsd:int' */
        int chn;
};
#endif

/* soap_gsmio.h:127 */
#ifndef SOAP_TYPE_ns__gsmio_get_pwr_status
#define SOAP_TYPE_ns__gsmio_get_pwr_status (23)
/* complex XSD type 'ns:gsmio-get-pwr-status': */
struct ns__gsmio_get_pwr_status {
        /** Required element 'chn' of XSD type 'xsd:int' */
        int chn;
};
#endif

/* soap_gsmio.h:130 */
#ifndef SOAP_TYPE_ns__gsmio_pwrkey_onResponse
#define SOAP_TYPE_ns__gsmio_pwrkey_onResponse (25)
/* complex XSD type 'ns:gsmio-pwrkey-onResponse': */
struct ns__gsmio_pwrkey_onResponse {
        /** Optional element 'result' of XSD type 'xsd:int' */
        int *result;
};
#endif

/* soap_gsmio.h:130 */
#ifndef SOAP_TYPE_ns__gsmio_pwrkey_on
#define SOAP_TYPE_ns__gsmio_pwrkey_on (26)
/* complex XSD type 'ns:gsmio-pwrkey-on': */
struct ns__gsmio_pwrkey_on {
        /** Required element 'chn' of XSD type 'xsd:int' */
        int chn;
};
#endif

/* soap_gsmio.h:133 */
#ifndef SOAP_TYPE_ns__gsmio_pwrkey_offResponse
#define SOAP_TYPE_ns__gsmio_pwrkey_offResponse (28)
/* complex XSD type 'ns:gsmio-pwrkey-offResponse': */
struct ns__gsmio_pwrkey_offResponse {
        /** Optional element 'result' of XSD type 'xsd:int' */
        int *result;
};
#endif

/* soap_gsmio.h:133 */
#ifndef SOAP_TYPE_ns__gsmio_pwrkey_off
#define SOAP_TYPE_ns__gsmio_pwrkey_off (29)
/* complex XSD type 'ns:gsmio-pwrkey-off': */
struct ns__gsmio_pwrkey_off {
        /** Required element 'chn' of XSD type 'xsd:int' */
        int chn;
};
#endif

/* soap_gsmio.h:136 */
#ifndef SOAP_TYPE_ns__gsmio_emerg_offResponse
#define SOAP_TYPE_ns__gsmio_emerg_offResponse (31)
/* complex XSD type 'ns:gsmio-emerg-offResponse': */
struct ns__gsmio_emerg_offResponse {
        /** Optional element 'result' of XSD type 'xsd:int' */
        int *result;
};
#endif

/* soap_gsmio.h:136 */
#ifndef SOAP_TYPE_ns__gsmio_emerg_off
#define SOAP_TYPE_ns__gsmio_emerg_off (32)
/* complex XSD type 'ns:gsmio-emerg-off': */
struct ns__gsmio_emerg_off {
        /** Required element 'chn' of XSD type 'xsd:int' */
        int chn;
};
#endif

/* soap_gsmio.h:139 */
#ifndef SOAP_TYPE_ns__gsmio_get_pwrkey_status
#define SOAP_TYPE_ns__gsmio_get_pwrkey_status (34)
/* complex XSD type 'ns:gsmio-get-pwrkey-status': */
struct ns__gsmio_get_pwrkey_status {
        /** Required element 'chn' of XSD type 'xsd:int' */
        int chn;
};
#endif

/* soap_gsmio.h:142 */
#ifndef SOAP_TYPE_ns__gsmio_get_simcard_insert_status
#define SOAP_TYPE_ns__gsmio_get_simcard_insert_status (36)
/* complex XSD type 'ns:gsmio-get-simcard-insert-status': */
struct ns__gsmio_get_simcard_insert_status {
        /** Required element 'chn' of XSD type 'xsd:int' */
        int chn;
};
#endif

/* soap_gsmio.h:145 */
#ifndef SOAP_TYPE_ns__gsmio_get_gsmboard_insert_status
#define SOAP_TYPE_ns__gsmio_get_gsmboard_insert_status (38)
/* complex XSD type 'ns:gsmio-get-gsmboard-insert-status': */
struct ns__gsmio_get_gsmboard_insert_status {
        /** Required element 'chn' of XSD type 'xsd:int' */
        int chn;
};
#endif

/* soap_gsmio.h:149 */
#ifndef SOAP_TYPE_ns__gsmio_get_mcu_versionResponse
#define SOAP_TYPE_ns__gsmio_get_mcu_versionResponse (41)
/* complex XSD type 'ns:gsmio-get-mcu-versionResponse': */
struct ns__gsmio_get_mcu_versionResponse {
        /** Optional element 'result' of XSD type 'xsd:string' */
        char **result;
};
#endif

/* soap_gsmio.h:149 */
#ifndef SOAP_TYPE_ns__gsmio_get_mcu_version
#define SOAP_TYPE_ns__gsmio_get_mcu_version (42)
/* complex XSD type 'ns:gsmio-get-mcu-version': */
struct ns__gsmio_get_mcu_version {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* soap_gsmio.h:153 */
#ifndef SOAP_TYPE_ns__gsmio_get_mcu_helpResponse
#define SOAP_TYPE_ns__gsmio_get_mcu_helpResponse (44)
/* complex XSD type 'ns:gsmio-get-mcu-helpResponse': */
struct ns__gsmio_get_mcu_helpResponse {
        /** Optional element 'result' of XSD type 'xsd:string' */
        char **result;
};
#endif

/* soap_gsmio.h:153 */
#ifndef SOAP_TYPE_ns__gsmio_get_mcu_help
#define SOAP_TYPE_ns__gsmio_get_mcu_help (45)
/* complex XSD type 'ns:gsmio-get-mcu-help': */
struct ns__gsmio_get_mcu_help {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif

/* soap_gsmio.h:155 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (46)
/* SOAP_ENV__Header: */
struct SOAP_ENV__Header {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif
#endif

/* soap_gsmio.h:155 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (47)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_ENV__Code {
        /** Optional element 'SOAP-ENV:Value' of XSD type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
};
#endif
#endif

/* soap_gsmio.h:155 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (49)
/* SOAP_ENV__Detail: */
struct SOAP_ENV__Detail {
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_T assigned to __type */
        /** Do not create a cyclic data structure throught this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
};
#endif
#endif

/* soap_gsmio.h:155 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (52)
/* SOAP_ENV__Reason: */
struct SOAP_ENV__Reason {
        /** Optional element 'SOAP-ENV:Text' of XSD type 'xsd:string' */
        char *SOAP_ENV__Text;
};
#endif
#endif

/* soap_gsmio.h:155 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (53)
/* SOAP_ENV__Fault: */
struct SOAP_ENV__Fault {
        /** Optional element 'faultcode' of XSD type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XSD type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XSD type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XSD type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XSD type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XSD type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* soap_gsmio.h:107 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

/* soap_gsmio.h:107 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

/* soap_gsmio.h:112 */
#ifndef SOAP_TYPE_ns__gsmio_rsp_t
#define SOAP_TYPE_ns__gsmio_rsp_t (8)
typedef struct ns__gsmio_rsp_s ns__gsmio_rsp_t;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (53)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (52)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (49)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (47)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (46)
#endif

/* struct ns__gsmio_get_mcu_help has binding name 'ns__gsmio_get_mcu_help' for type 'ns:gsmio-get-mcu-help' */
#ifndef SOAP_TYPE_ns__gsmio_get_mcu_help
#define SOAP_TYPE_ns__gsmio_get_mcu_help (45)
#endif

/* struct ns__gsmio_get_mcu_helpResponse has binding name 'ns__gsmio_get_mcu_helpResponse' for type 'ns:gsmio-get-mcu-helpResponse' */
#ifndef SOAP_TYPE_ns__gsmio_get_mcu_helpResponse
#define SOAP_TYPE_ns__gsmio_get_mcu_helpResponse (44)
#endif

/* struct ns__gsmio_get_mcu_version has binding name 'ns__gsmio_get_mcu_version' for type 'ns:gsmio-get-mcu-version' */
#ifndef SOAP_TYPE_ns__gsmio_get_mcu_version
#define SOAP_TYPE_ns__gsmio_get_mcu_version (42)
#endif

/* struct ns__gsmio_get_mcu_versionResponse has binding name 'ns__gsmio_get_mcu_versionResponse' for type 'ns:gsmio-get-mcu-versionResponse' */
#ifndef SOAP_TYPE_ns__gsmio_get_mcu_versionResponse
#define SOAP_TYPE_ns__gsmio_get_mcu_versionResponse (41)
#endif

/* struct ns__gsmio_get_gsmboard_insert_status has binding name 'ns__gsmio_get_gsmboard_insert_status' for type 'ns:gsmio-get-gsmboard-insert-status' */
#ifndef SOAP_TYPE_ns__gsmio_get_gsmboard_insert_status
#define SOAP_TYPE_ns__gsmio_get_gsmboard_insert_status (38)
#endif

/* struct ns__gsmio_get_simcard_insert_status has binding name 'ns__gsmio_get_simcard_insert_status' for type 'ns:gsmio-get-simcard-insert-status' */
#ifndef SOAP_TYPE_ns__gsmio_get_simcard_insert_status
#define SOAP_TYPE_ns__gsmio_get_simcard_insert_status (36)
#endif

/* struct ns__gsmio_get_pwrkey_status has binding name 'ns__gsmio_get_pwrkey_status' for type 'ns:gsmio-get-pwrkey-status' */
#ifndef SOAP_TYPE_ns__gsmio_get_pwrkey_status
#define SOAP_TYPE_ns__gsmio_get_pwrkey_status (34)
#endif

/* struct ns__gsmio_emerg_off has binding name 'ns__gsmio_emerg_off' for type 'ns:gsmio-emerg-off' */
#ifndef SOAP_TYPE_ns__gsmio_emerg_off
#define SOAP_TYPE_ns__gsmio_emerg_off (32)
#endif

/* struct ns__gsmio_emerg_offResponse has binding name 'ns__gsmio_emerg_offResponse' for type 'ns:gsmio-emerg-offResponse' */
#ifndef SOAP_TYPE_ns__gsmio_emerg_offResponse
#define SOAP_TYPE_ns__gsmio_emerg_offResponse (31)
#endif

/* struct ns__gsmio_pwrkey_off has binding name 'ns__gsmio_pwrkey_off' for type 'ns:gsmio-pwrkey-off' */
#ifndef SOAP_TYPE_ns__gsmio_pwrkey_off
#define SOAP_TYPE_ns__gsmio_pwrkey_off (29)
#endif

/* struct ns__gsmio_pwrkey_offResponse has binding name 'ns__gsmio_pwrkey_offResponse' for type 'ns:gsmio-pwrkey-offResponse' */
#ifndef SOAP_TYPE_ns__gsmio_pwrkey_offResponse
#define SOAP_TYPE_ns__gsmio_pwrkey_offResponse (28)
#endif

/* struct ns__gsmio_pwrkey_on has binding name 'ns__gsmio_pwrkey_on' for type 'ns:gsmio-pwrkey-on' */
#ifndef SOAP_TYPE_ns__gsmio_pwrkey_on
#define SOAP_TYPE_ns__gsmio_pwrkey_on (26)
#endif

/* struct ns__gsmio_pwrkey_onResponse has binding name 'ns__gsmio_pwrkey_onResponse' for type 'ns:gsmio-pwrkey-onResponse' */
#ifndef SOAP_TYPE_ns__gsmio_pwrkey_onResponse
#define SOAP_TYPE_ns__gsmio_pwrkey_onResponse (25)
#endif

/* struct ns__gsmio_get_pwr_status has binding name 'ns__gsmio_get_pwr_status' for type 'ns:gsmio-get-pwr-status' */
#ifndef SOAP_TYPE_ns__gsmio_get_pwr_status
#define SOAP_TYPE_ns__gsmio_get_pwr_status (23)
#endif

/* struct ns__gsmio_pwr_off has binding name 'ns__gsmio_pwr_off' for type 'ns:gsmio-pwr-off' */
#ifndef SOAP_TYPE_ns__gsmio_pwr_off
#define SOAP_TYPE_ns__gsmio_pwr_off (21)
#endif

/* struct ns__gsmio_pwr_offResponse has binding name 'ns__gsmio_pwr_offResponse' for type 'ns:gsmio-pwr-offResponse' */
#ifndef SOAP_TYPE_ns__gsmio_pwr_offResponse
#define SOAP_TYPE_ns__gsmio_pwr_offResponse (20)
#endif

/* struct ns__gsmio_pwr_on has binding name 'ns__gsmio_pwr_on' for type 'ns:gsmio-pwr-on' */
#ifndef SOAP_TYPE_ns__gsmio_pwr_on
#define SOAP_TYPE_ns__gsmio_pwr_on (18)
#endif

/* struct ns__gsmio_pwr_onResponse has binding name 'ns__gsmio_pwr_onResponse' for type 'ns:gsmio-pwr-onResponse' */
#ifndef SOAP_TYPE_ns__gsmio_pwr_onResponse
#define SOAP_TYPE_ns__gsmio_pwr_onResponse (17)
#endif

/* struct ns__gsmio_get_simcard_src has binding name 'ns__gsmio_get_simcard_src' for type 'ns:gsmio-get-simcard-src' */
#ifndef SOAP_TYPE_ns__gsmio_get_simcard_src
#define SOAP_TYPE_ns__gsmio_get_simcard_src (15)
#endif

/* struct ns__gsmio_set_simcard_src has binding name 'ns__gsmio_set_simcard_src' for type 'ns:gsmio-set-simcard-src' */
#ifndef SOAP_TYPE_ns__gsmio_set_simcard_src
#define SOAP_TYPE_ns__gsmio_set_simcard_src (12)
#endif

/* struct ns__gsmio_set_simcard_srcResponse has binding name 'ns__gsmio_set_simcard_srcResponse' for type 'ns:gsmio-set-simcard-srcResponse' */
#ifndef SOAP_TYPE_ns__gsmio_set_simcard_srcResponse
#define SOAP_TYPE_ns__gsmio_set_simcard_srcResponse (11)
#endif

/* ns__gsmio_rsp_t has binding name 'ns__gsmio_rsp_t' for type 'ns:gsmio-rsp-t' */
#ifndef SOAP_TYPE_ns__gsmio_rsp_t
#define SOAP_TYPE_ns__gsmio_rsp_t (8)
#endif

/* struct ns__gsmio_rsp_s has binding name 'ns__gsmio_rsp_s' for type 'ns:gsmio-rsp-s' */
#ifndef SOAP_TYPE_ns__gsmio_rsp_s
#define SOAP_TYPE_ns__gsmio_rsp_s (7)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (55)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (54)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (48)
#endif

/* char ** has binding name 'PointerTostring' for type 'xsd:string' */
#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (39)
#endif

/* struct ns__gsmio_rsp_s * has binding name 'PointerTons__gsmio_rsp_t' for type 'ns:gsmio-rsp-t' */
#ifndef SOAP_TYPE_PointerTons__gsmio_rsp_t
#define SOAP_TYPE_PointerTons__gsmio_rsp_t (13)
#endif

/* int * has binding name 'PointerToint' for type 'xsd:int' */
#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (9)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stub Functions                                            *
 *                                                                            *
\******************************************************************************/

    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_set_simcard_src(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, int src, int *result);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_get_simcard_src(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, struct ns__gsmio_rsp_s *result);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_pwr_on(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, int *result);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_pwr_off(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, int *result);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_get_pwr_status(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, struct ns__gsmio_rsp_s *result);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_pwrkey_on(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, int *result);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_pwrkey_off(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, int *result);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_emerg_off(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, int *result);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_get_pwrkey_status(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, struct ns__gsmio_rsp_s *result);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_get_simcard_insert_status(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, struct ns__gsmio_rsp_s *result);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_get_gsmboard_insert_status(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, struct ns__gsmio_rsp_s *result);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_get_mcu_version(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **result);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_get_mcu_help(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **result);

/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/

    /** Web service operation 'ns__gsmio_set_simcard_src' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns__gsmio_set_simcard_src(struct soap*, int chn, int src, int *result);
    /** Web service operation 'ns__gsmio_get_simcard_src' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns__gsmio_get_simcard_src(struct soap*, int chn, struct ns__gsmio_rsp_s *result);
    /** Web service operation 'ns__gsmio_pwr_on' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns__gsmio_pwr_on(struct soap*, int chn, int *result);
    /** Web service operation 'ns__gsmio_pwr_off' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns__gsmio_pwr_off(struct soap*, int chn, int *result);
    /** Web service operation 'ns__gsmio_get_pwr_status' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns__gsmio_get_pwr_status(struct soap*, int chn, struct ns__gsmio_rsp_s *result);
    /** Web service operation 'ns__gsmio_pwrkey_on' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns__gsmio_pwrkey_on(struct soap*, int chn, int *result);
    /** Web service operation 'ns__gsmio_pwrkey_off' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns__gsmio_pwrkey_off(struct soap*, int chn, int *result);
    /** Web service operation 'ns__gsmio_emerg_off' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns__gsmio_emerg_off(struct soap*, int chn, int *result);
    /** Web service operation 'ns__gsmio_get_pwrkey_status' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns__gsmio_get_pwrkey_status(struct soap*, int chn, struct ns__gsmio_rsp_s *result);
    /** Web service operation 'ns__gsmio_get_simcard_insert_status' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns__gsmio_get_simcard_insert_status(struct soap*, int chn, struct ns__gsmio_rsp_s *result);
    /** Web service operation 'ns__gsmio_get_gsmboard_insert_status' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns__gsmio_get_gsmboard_insert_status(struct soap*, int chn, struct ns__gsmio_rsp_s *result);
    /** Web service operation 'ns__gsmio_get_mcu_version' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns__gsmio_get_mcu_version(struct soap*, char **result);
    /** Web service operation 'ns__gsmio_get_mcu_help' (returns SOAP_OK or error code) */
    SOAP_FMAC5 int SOAP_FMAC6 ns__gsmio_get_mcu_help(struct soap*, char **result);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_set_simcard_src(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_get_simcard_src(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_pwr_on(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_pwr_off(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_get_pwr_status(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_pwrkey_on(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_pwrkey_off(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_emerg_off(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_get_pwrkey_status(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_get_simcard_insert_status(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_get_gsmboard_insert_status(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_get_mcu_version(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_get_mcu_help(struct soap*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
