/* soapH.h
   Generated by gSOAP 2.8.36 for soap_gsmio.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

#ifndef SOAP_TYPE_byte_DEFINED
#define SOAP_TYPE_byte_DEFINED

#ifdef SOAP_DEFAULT_byte
#define soap_default_byte(soap, a) (*(a) = SOAP_DEFAULT_byte)
#else
#define soap_default_byte(soap, a) (*(a) = (char)0)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 char * SOAP_FMAC4 soap_new_byte(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || soap_put_byte(soap, data, "byte", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_int_DEFINED
#define SOAP_TYPE_int_DEFINED

#ifdef SOAP_DEFAULT_int
#define soap_default_int(soap, a) (*(a) = SOAP_DEFAULT_int)
#else
#define soap_default_int(soap, a) (*(a) = (int)0)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int * SOAP_FMAC4 soap_new_int(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || soap_put_int(soap, data, "int", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault_DEFINED
#define SOAP_TYPE_SOAP_ENV__Fault_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_new_SOAP_ENV__Fault(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( ((data) ? (soap_default_SOAP_ENV__Fault(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason_DEFINED
#define SOAP_TYPE_SOAP_ENV__Reason_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_new_SOAP_ENV__Reason(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( ((data) ? (soap_default_SOAP_ENV__Reason(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail_DEFINED
#define SOAP_TYPE_SOAP_ENV__Detail_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_new_SOAP_ENV__Detail(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( ((data) ? (soap_default_SOAP_ENV__Detail(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code_DEFINED
#define SOAP_TYPE_SOAP_ENV__Code_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_new_SOAP_ENV__Code(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( ((data) ? (soap_default_SOAP_ENV__Code(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header_DEFINED
#define SOAP_TYPE_SOAP_ENV__Header_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_new_SOAP_ENV__Header(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( ((data) ? (soap_default_SOAP_ENV__Header(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_get_mcu_help_DEFINED
#define SOAP_TYPE_ns__gsmio_get_mcu_help_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_get_mcu_help(struct soap*, struct ns__gsmio_get_mcu_help *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_get_mcu_help(struct soap*, const struct ns__gsmio_get_mcu_help *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_get_mcu_help(struct soap*, const char*, int, const struct ns__gsmio_get_mcu_help *, const char*);
SOAP_FMAC3 struct ns__gsmio_get_mcu_help * SOAP_FMAC4 soap_in_ns__gsmio_get_mcu_help(struct soap*, const char*, struct ns__gsmio_get_mcu_help *, const char*);

SOAP_FMAC3 struct ns__gsmio_get_mcu_help * SOAP_FMAC4 soap_new_ns__gsmio_get_mcu_help(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_get_mcu_help(struct soap*, const struct ns__gsmio_get_mcu_help *, const char*, const char*);

#ifndef soap_write_ns__gsmio_get_mcu_help
#define soap_write_ns__gsmio_get_mcu_help(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_get_mcu_help(soap, data), 0) || soap_put_ns__gsmio_get_mcu_help(soap, data, "ns:gsmio-get-mcu-help", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_get_mcu_help * SOAP_FMAC4 soap_get_ns__gsmio_get_mcu_help(struct soap*, struct ns__gsmio_get_mcu_help *, const char*, const char*);

#ifndef soap_read_ns__gsmio_get_mcu_help
#define soap_read_ns__gsmio_get_mcu_help(soap, data) ( ((data) ? (soap_default_ns__gsmio_get_mcu_help(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_get_mcu_help(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_get_mcu_helpResponse_DEFINED
#define SOAP_TYPE_ns__gsmio_get_mcu_helpResponse_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_get_mcu_helpResponse(struct soap*, struct ns__gsmio_get_mcu_helpResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_get_mcu_helpResponse(struct soap*, const struct ns__gsmio_get_mcu_helpResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_get_mcu_helpResponse(struct soap*, const char*, int, const struct ns__gsmio_get_mcu_helpResponse *, const char*);
SOAP_FMAC3 struct ns__gsmio_get_mcu_helpResponse * SOAP_FMAC4 soap_in_ns__gsmio_get_mcu_helpResponse(struct soap*, const char*, struct ns__gsmio_get_mcu_helpResponse *, const char*);

SOAP_FMAC3 struct ns__gsmio_get_mcu_helpResponse * SOAP_FMAC4 soap_new_ns__gsmio_get_mcu_helpResponse(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_get_mcu_helpResponse(struct soap*, const struct ns__gsmio_get_mcu_helpResponse *, const char*, const char*);

#ifndef soap_write_ns__gsmio_get_mcu_helpResponse
#define soap_write_ns__gsmio_get_mcu_helpResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_get_mcu_helpResponse(soap, data), 0) || soap_put_ns__gsmio_get_mcu_helpResponse(soap, data, "ns:gsmio-get-mcu-helpResponse", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_get_mcu_helpResponse * SOAP_FMAC4 soap_get_ns__gsmio_get_mcu_helpResponse(struct soap*, struct ns__gsmio_get_mcu_helpResponse *, const char*, const char*);

#ifndef soap_read_ns__gsmio_get_mcu_helpResponse
#define soap_read_ns__gsmio_get_mcu_helpResponse(soap, data) ( ((data) ? (soap_default_ns__gsmio_get_mcu_helpResponse(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_get_mcu_helpResponse(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_get_mcu_version_DEFINED
#define SOAP_TYPE_ns__gsmio_get_mcu_version_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_get_mcu_version(struct soap*, struct ns__gsmio_get_mcu_version *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_get_mcu_version(struct soap*, const struct ns__gsmio_get_mcu_version *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_get_mcu_version(struct soap*, const char*, int, const struct ns__gsmio_get_mcu_version *, const char*);
SOAP_FMAC3 struct ns__gsmio_get_mcu_version * SOAP_FMAC4 soap_in_ns__gsmio_get_mcu_version(struct soap*, const char*, struct ns__gsmio_get_mcu_version *, const char*);

SOAP_FMAC3 struct ns__gsmio_get_mcu_version * SOAP_FMAC4 soap_new_ns__gsmio_get_mcu_version(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_get_mcu_version(struct soap*, const struct ns__gsmio_get_mcu_version *, const char*, const char*);

#ifndef soap_write_ns__gsmio_get_mcu_version
#define soap_write_ns__gsmio_get_mcu_version(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_get_mcu_version(soap, data), 0) || soap_put_ns__gsmio_get_mcu_version(soap, data, "ns:gsmio-get-mcu-version", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_get_mcu_version * SOAP_FMAC4 soap_get_ns__gsmio_get_mcu_version(struct soap*, struct ns__gsmio_get_mcu_version *, const char*, const char*);

#ifndef soap_read_ns__gsmio_get_mcu_version
#define soap_read_ns__gsmio_get_mcu_version(soap, data) ( ((data) ? (soap_default_ns__gsmio_get_mcu_version(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_get_mcu_version(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_get_mcu_versionResponse_DEFINED
#define SOAP_TYPE_ns__gsmio_get_mcu_versionResponse_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_get_mcu_versionResponse(struct soap*, struct ns__gsmio_get_mcu_versionResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_get_mcu_versionResponse(struct soap*, const struct ns__gsmio_get_mcu_versionResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_get_mcu_versionResponse(struct soap*, const char*, int, const struct ns__gsmio_get_mcu_versionResponse *, const char*);
SOAP_FMAC3 struct ns__gsmio_get_mcu_versionResponse * SOAP_FMAC4 soap_in_ns__gsmio_get_mcu_versionResponse(struct soap*, const char*, struct ns__gsmio_get_mcu_versionResponse *, const char*);

SOAP_FMAC3 struct ns__gsmio_get_mcu_versionResponse * SOAP_FMAC4 soap_new_ns__gsmio_get_mcu_versionResponse(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_get_mcu_versionResponse(struct soap*, const struct ns__gsmio_get_mcu_versionResponse *, const char*, const char*);

#ifndef soap_write_ns__gsmio_get_mcu_versionResponse
#define soap_write_ns__gsmio_get_mcu_versionResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_get_mcu_versionResponse(soap, data), 0) || soap_put_ns__gsmio_get_mcu_versionResponse(soap, data, "ns:gsmio-get-mcu-versionResponse", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_get_mcu_versionResponse * SOAP_FMAC4 soap_get_ns__gsmio_get_mcu_versionResponse(struct soap*, struct ns__gsmio_get_mcu_versionResponse *, const char*, const char*);

#ifndef soap_read_ns__gsmio_get_mcu_versionResponse
#define soap_read_ns__gsmio_get_mcu_versionResponse(soap, data) ( ((data) ? (soap_default_ns__gsmio_get_mcu_versionResponse(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_get_mcu_versionResponse(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_get_gsmboard_insert_status_DEFINED
#define SOAP_TYPE_ns__gsmio_get_gsmboard_insert_status_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_get_gsmboard_insert_status(struct soap*, struct ns__gsmio_get_gsmboard_insert_status *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_get_gsmboard_insert_status(struct soap*, const struct ns__gsmio_get_gsmboard_insert_status *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_get_gsmboard_insert_status(struct soap*, const char*, int, const struct ns__gsmio_get_gsmboard_insert_status *, const char*);
SOAP_FMAC3 struct ns__gsmio_get_gsmboard_insert_status * SOAP_FMAC4 soap_in_ns__gsmio_get_gsmboard_insert_status(struct soap*, const char*, struct ns__gsmio_get_gsmboard_insert_status *, const char*);

SOAP_FMAC3 struct ns__gsmio_get_gsmboard_insert_status * SOAP_FMAC4 soap_new_ns__gsmio_get_gsmboard_insert_status(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_get_gsmboard_insert_status(struct soap*, const struct ns__gsmio_get_gsmboard_insert_status *, const char*, const char*);

#ifndef soap_write_ns__gsmio_get_gsmboard_insert_status
#define soap_write_ns__gsmio_get_gsmboard_insert_status(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_get_gsmboard_insert_status(soap, data), 0) || soap_put_ns__gsmio_get_gsmboard_insert_status(soap, data, "ns:gsmio-get-gsmboard-insert-status", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_get_gsmboard_insert_status * SOAP_FMAC4 soap_get_ns__gsmio_get_gsmboard_insert_status(struct soap*, struct ns__gsmio_get_gsmboard_insert_status *, const char*, const char*);

#ifndef soap_read_ns__gsmio_get_gsmboard_insert_status
#define soap_read_ns__gsmio_get_gsmboard_insert_status(soap, data) ( ((data) ? (soap_default_ns__gsmio_get_gsmboard_insert_status(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_get_gsmboard_insert_status(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_get_simcard_insert_status_DEFINED
#define SOAP_TYPE_ns__gsmio_get_simcard_insert_status_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_get_simcard_insert_status(struct soap*, struct ns__gsmio_get_simcard_insert_status *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_get_simcard_insert_status(struct soap*, const struct ns__gsmio_get_simcard_insert_status *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_get_simcard_insert_status(struct soap*, const char*, int, const struct ns__gsmio_get_simcard_insert_status *, const char*);
SOAP_FMAC3 struct ns__gsmio_get_simcard_insert_status * SOAP_FMAC4 soap_in_ns__gsmio_get_simcard_insert_status(struct soap*, const char*, struct ns__gsmio_get_simcard_insert_status *, const char*);

SOAP_FMAC3 struct ns__gsmio_get_simcard_insert_status * SOAP_FMAC4 soap_new_ns__gsmio_get_simcard_insert_status(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_get_simcard_insert_status(struct soap*, const struct ns__gsmio_get_simcard_insert_status *, const char*, const char*);

#ifndef soap_write_ns__gsmio_get_simcard_insert_status
#define soap_write_ns__gsmio_get_simcard_insert_status(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_get_simcard_insert_status(soap, data), 0) || soap_put_ns__gsmio_get_simcard_insert_status(soap, data, "ns:gsmio-get-simcard-insert-status", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_get_simcard_insert_status * SOAP_FMAC4 soap_get_ns__gsmio_get_simcard_insert_status(struct soap*, struct ns__gsmio_get_simcard_insert_status *, const char*, const char*);

#ifndef soap_read_ns__gsmio_get_simcard_insert_status
#define soap_read_ns__gsmio_get_simcard_insert_status(soap, data) ( ((data) ? (soap_default_ns__gsmio_get_simcard_insert_status(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_get_simcard_insert_status(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_get_pwrkey_status_DEFINED
#define SOAP_TYPE_ns__gsmio_get_pwrkey_status_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_get_pwrkey_status(struct soap*, struct ns__gsmio_get_pwrkey_status *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_get_pwrkey_status(struct soap*, const struct ns__gsmio_get_pwrkey_status *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_get_pwrkey_status(struct soap*, const char*, int, const struct ns__gsmio_get_pwrkey_status *, const char*);
SOAP_FMAC3 struct ns__gsmio_get_pwrkey_status * SOAP_FMAC4 soap_in_ns__gsmio_get_pwrkey_status(struct soap*, const char*, struct ns__gsmio_get_pwrkey_status *, const char*);

SOAP_FMAC3 struct ns__gsmio_get_pwrkey_status * SOAP_FMAC4 soap_new_ns__gsmio_get_pwrkey_status(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_get_pwrkey_status(struct soap*, const struct ns__gsmio_get_pwrkey_status *, const char*, const char*);

#ifndef soap_write_ns__gsmio_get_pwrkey_status
#define soap_write_ns__gsmio_get_pwrkey_status(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_get_pwrkey_status(soap, data), 0) || soap_put_ns__gsmio_get_pwrkey_status(soap, data, "ns:gsmio-get-pwrkey-status", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_get_pwrkey_status * SOAP_FMAC4 soap_get_ns__gsmio_get_pwrkey_status(struct soap*, struct ns__gsmio_get_pwrkey_status *, const char*, const char*);

#ifndef soap_read_ns__gsmio_get_pwrkey_status
#define soap_read_ns__gsmio_get_pwrkey_status(soap, data) ( ((data) ? (soap_default_ns__gsmio_get_pwrkey_status(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_get_pwrkey_status(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_emerg_off_DEFINED
#define SOAP_TYPE_ns__gsmio_emerg_off_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_emerg_off(struct soap*, struct ns__gsmio_emerg_off *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_emerg_off(struct soap*, const struct ns__gsmio_emerg_off *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_emerg_off(struct soap*, const char*, int, const struct ns__gsmio_emerg_off *, const char*);
SOAP_FMAC3 struct ns__gsmio_emerg_off * SOAP_FMAC4 soap_in_ns__gsmio_emerg_off(struct soap*, const char*, struct ns__gsmio_emerg_off *, const char*);

SOAP_FMAC3 struct ns__gsmio_emerg_off * SOAP_FMAC4 soap_new_ns__gsmio_emerg_off(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_emerg_off(struct soap*, const struct ns__gsmio_emerg_off *, const char*, const char*);

#ifndef soap_write_ns__gsmio_emerg_off
#define soap_write_ns__gsmio_emerg_off(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_emerg_off(soap, data), 0) || soap_put_ns__gsmio_emerg_off(soap, data, "ns:gsmio-emerg-off", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_emerg_off * SOAP_FMAC4 soap_get_ns__gsmio_emerg_off(struct soap*, struct ns__gsmio_emerg_off *, const char*, const char*);

#ifndef soap_read_ns__gsmio_emerg_off
#define soap_read_ns__gsmio_emerg_off(soap, data) ( ((data) ? (soap_default_ns__gsmio_emerg_off(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_emerg_off(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_emerg_offResponse_DEFINED
#define SOAP_TYPE_ns__gsmio_emerg_offResponse_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_emerg_offResponse(struct soap*, struct ns__gsmio_emerg_offResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_emerg_offResponse(struct soap*, const struct ns__gsmio_emerg_offResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_emerg_offResponse(struct soap*, const char*, int, const struct ns__gsmio_emerg_offResponse *, const char*);
SOAP_FMAC3 struct ns__gsmio_emerg_offResponse * SOAP_FMAC4 soap_in_ns__gsmio_emerg_offResponse(struct soap*, const char*, struct ns__gsmio_emerg_offResponse *, const char*);

SOAP_FMAC3 struct ns__gsmio_emerg_offResponse * SOAP_FMAC4 soap_new_ns__gsmio_emerg_offResponse(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_emerg_offResponse(struct soap*, const struct ns__gsmio_emerg_offResponse *, const char*, const char*);

#ifndef soap_write_ns__gsmio_emerg_offResponse
#define soap_write_ns__gsmio_emerg_offResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_emerg_offResponse(soap, data), 0) || soap_put_ns__gsmio_emerg_offResponse(soap, data, "ns:gsmio-emerg-offResponse", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_emerg_offResponse * SOAP_FMAC4 soap_get_ns__gsmio_emerg_offResponse(struct soap*, struct ns__gsmio_emerg_offResponse *, const char*, const char*);

#ifndef soap_read_ns__gsmio_emerg_offResponse
#define soap_read_ns__gsmio_emerg_offResponse(soap, data) ( ((data) ? (soap_default_ns__gsmio_emerg_offResponse(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_emerg_offResponse(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_pwrkey_off_DEFINED
#define SOAP_TYPE_ns__gsmio_pwrkey_off_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_pwrkey_off(struct soap*, struct ns__gsmio_pwrkey_off *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_pwrkey_off(struct soap*, const struct ns__gsmio_pwrkey_off *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_pwrkey_off(struct soap*, const char*, int, const struct ns__gsmio_pwrkey_off *, const char*);
SOAP_FMAC3 struct ns__gsmio_pwrkey_off * SOAP_FMAC4 soap_in_ns__gsmio_pwrkey_off(struct soap*, const char*, struct ns__gsmio_pwrkey_off *, const char*);

SOAP_FMAC3 struct ns__gsmio_pwrkey_off * SOAP_FMAC4 soap_new_ns__gsmio_pwrkey_off(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_pwrkey_off(struct soap*, const struct ns__gsmio_pwrkey_off *, const char*, const char*);

#ifndef soap_write_ns__gsmio_pwrkey_off
#define soap_write_ns__gsmio_pwrkey_off(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_pwrkey_off(soap, data), 0) || soap_put_ns__gsmio_pwrkey_off(soap, data, "ns:gsmio-pwrkey-off", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_pwrkey_off * SOAP_FMAC4 soap_get_ns__gsmio_pwrkey_off(struct soap*, struct ns__gsmio_pwrkey_off *, const char*, const char*);

#ifndef soap_read_ns__gsmio_pwrkey_off
#define soap_read_ns__gsmio_pwrkey_off(soap, data) ( ((data) ? (soap_default_ns__gsmio_pwrkey_off(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_pwrkey_off(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_pwrkey_offResponse_DEFINED
#define SOAP_TYPE_ns__gsmio_pwrkey_offResponse_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_pwrkey_offResponse(struct soap*, struct ns__gsmio_pwrkey_offResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_pwrkey_offResponse(struct soap*, const struct ns__gsmio_pwrkey_offResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_pwrkey_offResponse(struct soap*, const char*, int, const struct ns__gsmio_pwrkey_offResponse *, const char*);
SOAP_FMAC3 struct ns__gsmio_pwrkey_offResponse * SOAP_FMAC4 soap_in_ns__gsmio_pwrkey_offResponse(struct soap*, const char*, struct ns__gsmio_pwrkey_offResponse *, const char*);

SOAP_FMAC3 struct ns__gsmio_pwrkey_offResponse * SOAP_FMAC4 soap_new_ns__gsmio_pwrkey_offResponse(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_pwrkey_offResponse(struct soap*, const struct ns__gsmio_pwrkey_offResponse *, const char*, const char*);

#ifndef soap_write_ns__gsmio_pwrkey_offResponse
#define soap_write_ns__gsmio_pwrkey_offResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_pwrkey_offResponse(soap, data), 0) || soap_put_ns__gsmio_pwrkey_offResponse(soap, data, "ns:gsmio-pwrkey-offResponse", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_pwrkey_offResponse * SOAP_FMAC4 soap_get_ns__gsmio_pwrkey_offResponse(struct soap*, struct ns__gsmio_pwrkey_offResponse *, const char*, const char*);

#ifndef soap_read_ns__gsmio_pwrkey_offResponse
#define soap_read_ns__gsmio_pwrkey_offResponse(soap, data) ( ((data) ? (soap_default_ns__gsmio_pwrkey_offResponse(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_pwrkey_offResponse(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_pwrkey_on_DEFINED
#define SOAP_TYPE_ns__gsmio_pwrkey_on_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_pwrkey_on(struct soap*, struct ns__gsmio_pwrkey_on *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_pwrkey_on(struct soap*, const struct ns__gsmio_pwrkey_on *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_pwrkey_on(struct soap*, const char*, int, const struct ns__gsmio_pwrkey_on *, const char*);
SOAP_FMAC3 struct ns__gsmio_pwrkey_on * SOAP_FMAC4 soap_in_ns__gsmio_pwrkey_on(struct soap*, const char*, struct ns__gsmio_pwrkey_on *, const char*);

SOAP_FMAC3 struct ns__gsmio_pwrkey_on * SOAP_FMAC4 soap_new_ns__gsmio_pwrkey_on(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_pwrkey_on(struct soap*, const struct ns__gsmio_pwrkey_on *, const char*, const char*);

#ifndef soap_write_ns__gsmio_pwrkey_on
#define soap_write_ns__gsmio_pwrkey_on(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_pwrkey_on(soap, data), 0) || soap_put_ns__gsmio_pwrkey_on(soap, data, "ns:gsmio-pwrkey-on", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_pwrkey_on * SOAP_FMAC4 soap_get_ns__gsmio_pwrkey_on(struct soap*, struct ns__gsmio_pwrkey_on *, const char*, const char*);

#ifndef soap_read_ns__gsmio_pwrkey_on
#define soap_read_ns__gsmio_pwrkey_on(soap, data) ( ((data) ? (soap_default_ns__gsmio_pwrkey_on(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_pwrkey_on(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_pwrkey_onResponse_DEFINED
#define SOAP_TYPE_ns__gsmio_pwrkey_onResponse_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_pwrkey_onResponse(struct soap*, struct ns__gsmio_pwrkey_onResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_pwrkey_onResponse(struct soap*, const struct ns__gsmio_pwrkey_onResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_pwrkey_onResponse(struct soap*, const char*, int, const struct ns__gsmio_pwrkey_onResponse *, const char*);
SOAP_FMAC3 struct ns__gsmio_pwrkey_onResponse * SOAP_FMAC4 soap_in_ns__gsmio_pwrkey_onResponse(struct soap*, const char*, struct ns__gsmio_pwrkey_onResponse *, const char*);

SOAP_FMAC3 struct ns__gsmio_pwrkey_onResponse * SOAP_FMAC4 soap_new_ns__gsmio_pwrkey_onResponse(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_pwrkey_onResponse(struct soap*, const struct ns__gsmio_pwrkey_onResponse *, const char*, const char*);

#ifndef soap_write_ns__gsmio_pwrkey_onResponse
#define soap_write_ns__gsmio_pwrkey_onResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_pwrkey_onResponse(soap, data), 0) || soap_put_ns__gsmio_pwrkey_onResponse(soap, data, "ns:gsmio-pwrkey-onResponse", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_pwrkey_onResponse * SOAP_FMAC4 soap_get_ns__gsmio_pwrkey_onResponse(struct soap*, struct ns__gsmio_pwrkey_onResponse *, const char*, const char*);

#ifndef soap_read_ns__gsmio_pwrkey_onResponse
#define soap_read_ns__gsmio_pwrkey_onResponse(soap, data) ( ((data) ? (soap_default_ns__gsmio_pwrkey_onResponse(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_pwrkey_onResponse(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_get_pwr_status_DEFINED
#define SOAP_TYPE_ns__gsmio_get_pwr_status_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_get_pwr_status(struct soap*, struct ns__gsmio_get_pwr_status *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_get_pwr_status(struct soap*, const struct ns__gsmio_get_pwr_status *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_get_pwr_status(struct soap*, const char*, int, const struct ns__gsmio_get_pwr_status *, const char*);
SOAP_FMAC3 struct ns__gsmio_get_pwr_status * SOAP_FMAC4 soap_in_ns__gsmio_get_pwr_status(struct soap*, const char*, struct ns__gsmio_get_pwr_status *, const char*);

SOAP_FMAC3 struct ns__gsmio_get_pwr_status * SOAP_FMAC4 soap_new_ns__gsmio_get_pwr_status(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_get_pwr_status(struct soap*, const struct ns__gsmio_get_pwr_status *, const char*, const char*);

#ifndef soap_write_ns__gsmio_get_pwr_status
#define soap_write_ns__gsmio_get_pwr_status(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_get_pwr_status(soap, data), 0) || soap_put_ns__gsmio_get_pwr_status(soap, data, "ns:gsmio-get-pwr-status", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_get_pwr_status * SOAP_FMAC4 soap_get_ns__gsmio_get_pwr_status(struct soap*, struct ns__gsmio_get_pwr_status *, const char*, const char*);

#ifndef soap_read_ns__gsmio_get_pwr_status
#define soap_read_ns__gsmio_get_pwr_status(soap, data) ( ((data) ? (soap_default_ns__gsmio_get_pwr_status(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_get_pwr_status(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_pwr_off_DEFINED
#define SOAP_TYPE_ns__gsmio_pwr_off_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_pwr_off(struct soap*, struct ns__gsmio_pwr_off *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_pwr_off(struct soap*, const struct ns__gsmio_pwr_off *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_pwr_off(struct soap*, const char*, int, const struct ns__gsmio_pwr_off *, const char*);
SOAP_FMAC3 struct ns__gsmio_pwr_off * SOAP_FMAC4 soap_in_ns__gsmio_pwr_off(struct soap*, const char*, struct ns__gsmio_pwr_off *, const char*);

SOAP_FMAC3 struct ns__gsmio_pwr_off * SOAP_FMAC4 soap_new_ns__gsmio_pwr_off(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_pwr_off(struct soap*, const struct ns__gsmio_pwr_off *, const char*, const char*);

#ifndef soap_write_ns__gsmio_pwr_off
#define soap_write_ns__gsmio_pwr_off(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_pwr_off(soap, data), 0) || soap_put_ns__gsmio_pwr_off(soap, data, "ns:gsmio-pwr-off", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_pwr_off * SOAP_FMAC4 soap_get_ns__gsmio_pwr_off(struct soap*, struct ns__gsmio_pwr_off *, const char*, const char*);

#ifndef soap_read_ns__gsmio_pwr_off
#define soap_read_ns__gsmio_pwr_off(soap, data) ( ((data) ? (soap_default_ns__gsmio_pwr_off(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_pwr_off(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_pwr_offResponse_DEFINED
#define SOAP_TYPE_ns__gsmio_pwr_offResponse_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_pwr_offResponse(struct soap*, struct ns__gsmio_pwr_offResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_pwr_offResponse(struct soap*, const struct ns__gsmio_pwr_offResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_pwr_offResponse(struct soap*, const char*, int, const struct ns__gsmio_pwr_offResponse *, const char*);
SOAP_FMAC3 struct ns__gsmio_pwr_offResponse * SOAP_FMAC4 soap_in_ns__gsmio_pwr_offResponse(struct soap*, const char*, struct ns__gsmio_pwr_offResponse *, const char*);

SOAP_FMAC3 struct ns__gsmio_pwr_offResponse * SOAP_FMAC4 soap_new_ns__gsmio_pwr_offResponse(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_pwr_offResponse(struct soap*, const struct ns__gsmio_pwr_offResponse *, const char*, const char*);

#ifndef soap_write_ns__gsmio_pwr_offResponse
#define soap_write_ns__gsmio_pwr_offResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_pwr_offResponse(soap, data), 0) || soap_put_ns__gsmio_pwr_offResponse(soap, data, "ns:gsmio-pwr-offResponse", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_pwr_offResponse * SOAP_FMAC4 soap_get_ns__gsmio_pwr_offResponse(struct soap*, struct ns__gsmio_pwr_offResponse *, const char*, const char*);

#ifndef soap_read_ns__gsmio_pwr_offResponse
#define soap_read_ns__gsmio_pwr_offResponse(soap, data) ( ((data) ? (soap_default_ns__gsmio_pwr_offResponse(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_pwr_offResponse(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_pwr_on_DEFINED
#define SOAP_TYPE_ns__gsmio_pwr_on_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_pwr_on(struct soap*, struct ns__gsmio_pwr_on *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_pwr_on(struct soap*, const struct ns__gsmio_pwr_on *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_pwr_on(struct soap*, const char*, int, const struct ns__gsmio_pwr_on *, const char*);
SOAP_FMAC3 struct ns__gsmio_pwr_on * SOAP_FMAC4 soap_in_ns__gsmio_pwr_on(struct soap*, const char*, struct ns__gsmio_pwr_on *, const char*);

SOAP_FMAC3 struct ns__gsmio_pwr_on * SOAP_FMAC4 soap_new_ns__gsmio_pwr_on(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_pwr_on(struct soap*, const struct ns__gsmio_pwr_on *, const char*, const char*);

#ifndef soap_write_ns__gsmio_pwr_on
#define soap_write_ns__gsmio_pwr_on(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_pwr_on(soap, data), 0) || soap_put_ns__gsmio_pwr_on(soap, data, "ns:gsmio-pwr-on", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_pwr_on * SOAP_FMAC4 soap_get_ns__gsmio_pwr_on(struct soap*, struct ns__gsmio_pwr_on *, const char*, const char*);

#ifndef soap_read_ns__gsmio_pwr_on
#define soap_read_ns__gsmio_pwr_on(soap, data) ( ((data) ? (soap_default_ns__gsmio_pwr_on(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_pwr_on(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_pwr_onResponse_DEFINED
#define SOAP_TYPE_ns__gsmio_pwr_onResponse_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_pwr_onResponse(struct soap*, struct ns__gsmio_pwr_onResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_pwr_onResponse(struct soap*, const struct ns__gsmio_pwr_onResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_pwr_onResponse(struct soap*, const char*, int, const struct ns__gsmio_pwr_onResponse *, const char*);
SOAP_FMAC3 struct ns__gsmio_pwr_onResponse * SOAP_FMAC4 soap_in_ns__gsmio_pwr_onResponse(struct soap*, const char*, struct ns__gsmio_pwr_onResponse *, const char*);

SOAP_FMAC3 struct ns__gsmio_pwr_onResponse * SOAP_FMAC4 soap_new_ns__gsmio_pwr_onResponse(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_pwr_onResponse(struct soap*, const struct ns__gsmio_pwr_onResponse *, const char*, const char*);

#ifndef soap_write_ns__gsmio_pwr_onResponse
#define soap_write_ns__gsmio_pwr_onResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_pwr_onResponse(soap, data), 0) || soap_put_ns__gsmio_pwr_onResponse(soap, data, "ns:gsmio-pwr-onResponse", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_pwr_onResponse * SOAP_FMAC4 soap_get_ns__gsmio_pwr_onResponse(struct soap*, struct ns__gsmio_pwr_onResponse *, const char*, const char*);

#ifndef soap_read_ns__gsmio_pwr_onResponse
#define soap_read_ns__gsmio_pwr_onResponse(soap, data) ( ((data) ? (soap_default_ns__gsmio_pwr_onResponse(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_pwr_onResponse(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_get_simcard_src_DEFINED
#define SOAP_TYPE_ns__gsmio_get_simcard_src_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_get_simcard_src(struct soap*, struct ns__gsmio_get_simcard_src *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_get_simcard_src(struct soap*, const struct ns__gsmio_get_simcard_src *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_get_simcard_src(struct soap*, const char*, int, const struct ns__gsmio_get_simcard_src *, const char*);
SOAP_FMAC3 struct ns__gsmio_get_simcard_src * SOAP_FMAC4 soap_in_ns__gsmio_get_simcard_src(struct soap*, const char*, struct ns__gsmio_get_simcard_src *, const char*);

SOAP_FMAC3 struct ns__gsmio_get_simcard_src * SOAP_FMAC4 soap_new_ns__gsmio_get_simcard_src(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_get_simcard_src(struct soap*, const struct ns__gsmio_get_simcard_src *, const char*, const char*);

#ifndef soap_write_ns__gsmio_get_simcard_src
#define soap_write_ns__gsmio_get_simcard_src(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_get_simcard_src(soap, data), 0) || soap_put_ns__gsmio_get_simcard_src(soap, data, "ns:gsmio-get-simcard-src", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_get_simcard_src * SOAP_FMAC4 soap_get_ns__gsmio_get_simcard_src(struct soap*, struct ns__gsmio_get_simcard_src *, const char*, const char*);

#ifndef soap_read_ns__gsmio_get_simcard_src
#define soap_read_ns__gsmio_get_simcard_src(soap, data) ( ((data) ? (soap_default_ns__gsmio_get_simcard_src(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_get_simcard_src(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_set_simcard_src_DEFINED
#define SOAP_TYPE_ns__gsmio_set_simcard_src_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_set_simcard_src(struct soap*, struct ns__gsmio_set_simcard_src *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_set_simcard_src(struct soap*, const struct ns__gsmio_set_simcard_src *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_set_simcard_src(struct soap*, const char*, int, const struct ns__gsmio_set_simcard_src *, const char*);
SOAP_FMAC3 struct ns__gsmio_set_simcard_src * SOAP_FMAC4 soap_in_ns__gsmio_set_simcard_src(struct soap*, const char*, struct ns__gsmio_set_simcard_src *, const char*);

SOAP_FMAC3 struct ns__gsmio_set_simcard_src * SOAP_FMAC4 soap_new_ns__gsmio_set_simcard_src(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_set_simcard_src(struct soap*, const struct ns__gsmio_set_simcard_src *, const char*, const char*);

#ifndef soap_write_ns__gsmio_set_simcard_src
#define soap_write_ns__gsmio_set_simcard_src(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_set_simcard_src(soap, data), 0) || soap_put_ns__gsmio_set_simcard_src(soap, data, "ns:gsmio-set-simcard-src", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_set_simcard_src * SOAP_FMAC4 soap_get_ns__gsmio_set_simcard_src(struct soap*, struct ns__gsmio_set_simcard_src *, const char*, const char*);

#ifndef soap_read_ns__gsmio_set_simcard_src
#define soap_read_ns__gsmio_set_simcard_src(soap, data) ( ((data) ? (soap_default_ns__gsmio_set_simcard_src(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_set_simcard_src(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_set_simcard_srcResponse_DEFINED
#define SOAP_TYPE_ns__gsmio_set_simcard_srcResponse_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_set_simcard_srcResponse(struct soap*, struct ns__gsmio_set_simcard_srcResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_set_simcard_srcResponse(struct soap*, const struct ns__gsmio_set_simcard_srcResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_set_simcard_srcResponse(struct soap*, const char*, int, const struct ns__gsmio_set_simcard_srcResponse *, const char*);
SOAP_FMAC3 struct ns__gsmio_set_simcard_srcResponse * SOAP_FMAC4 soap_in_ns__gsmio_set_simcard_srcResponse(struct soap*, const char*, struct ns__gsmio_set_simcard_srcResponse *, const char*);

SOAP_FMAC3 struct ns__gsmio_set_simcard_srcResponse * SOAP_FMAC4 soap_new_ns__gsmio_set_simcard_srcResponse(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_set_simcard_srcResponse(struct soap*, const struct ns__gsmio_set_simcard_srcResponse *, const char*, const char*);

#ifndef soap_write_ns__gsmio_set_simcard_srcResponse
#define soap_write_ns__gsmio_set_simcard_srcResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_set_simcard_srcResponse(soap, data), 0) || soap_put_ns__gsmio_set_simcard_srcResponse(soap, data, "ns:gsmio-set-simcard-srcResponse", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_set_simcard_srcResponse * SOAP_FMAC4 soap_get_ns__gsmio_set_simcard_srcResponse(struct soap*, struct ns__gsmio_set_simcard_srcResponse *, const char*, const char*);

#ifndef soap_read_ns__gsmio_set_simcard_srcResponse
#define soap_read_ns__gsmio_set_simcard_srcResponse(soap, data) ( ((data) ? (soap_default_ns__gsmio_set_simcard_srcResponse(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_set_simcard_srcResponse(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_rsp_t_DEFINED
#define SOAP_TYPE_ns__gsmio_rsp_t_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_rsp_t(struct soap*, struct ns__gsmio_rsp_s *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_rsp_t(struct soap*, const struct ns__gsmio_rsp_s *);

#define soap_ns__gsmio_rsp_t2s soap_ns__gsmio_rsp_s2s

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_rsp_t(struct soap*, const char*, int, const struct ns__gsmio_rsp_s *, const char*);

#define soap_s2ns__gsmio_rsp_t soap_s2ns__gsmio_rsp_s

SOAP_FMAC3 struct ns__gsmio_rsp_s * SOAP_FMAC4 soap_in_ns__gsmio_rsp_t(struct soap*, const char*, struct ns__gsmio_rsp_s *, const char*);
#define soap_new_ns__gsmio_rsp_t soap_new_ns__gsmio_rsp_s

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_rsp_t(struct soap*, const struct ns__gsmio_rsp_s *, const char*, const char*);

#ifndef soap_write_ns__gsmio_rsp_t
#define soap_write_ns__gsmio_rsp_t(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_rsp_t(soap, data), 0) || soap_put_ns__gsmio_rsp_t(soap, data, "ns:gsmio-rsp-t", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_rsp_s * SOAP_FMAC4 soap_get_ns__gsmio_rsp_t(struct soap*, struct ns__gsmio_rsp_s *, const char*, const char*);

#ifndef soap_read_ns__gsmio_rsp_t
#define soap_read_ns__gsmio_rsp_t(soap, data) ( ((data) ? (soap_default_ns__gsmio_rsp_t(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_rsp_t(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_ns__gsmio_rsp_s_DEFINED
#define SOAP_TYPE_ns__gsmio_rsp_s_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__gsmio_rsp_s(struct soap*, struct ns__gsmio_rsp_s *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__gsmio_rsp_s(struct soap*, const struct ns__gsmio_rsp_s *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__gsmio_rsp_s(struct soap*, const char*, int, const struct ns__gsmio_rsp_s *, const char*);
SOAP_FMAC3 struct ns__gsmio_rsp_s * SOAP_FMAC4 soap_in_ns__gsmio_rsp_s(struct soap*, const char*, struct ns__gsmio_rsp_s *, const char*);

SOAP_FMAC3 struct ns__gsmio_rsp_s * SOAP_FMAC4 soap_new_ns__gsmio_rsp_s(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__gsmio_rsp_s(struct soap*, const struct ns__gsmio_rsp_s *, const char*, const char*);

#ifndef soap_write_ns__gsmio_rsp_s
#define soap_write_ns__gsmio_rsp_s(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__gsmio_rsp_s(soap, data), 0) || soap_put_ns__gsmio_rsp_s(soap, data, "ns:gsmio-rsp-s", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__gsmio_rsp_s * SOAP_FMAC4 soap_get_ns__gsmio_rsp_s(struct soap*, struct ns__gsmio_rsp_s *, const char*, const char*);

#ifndef soap_read_ns__gsmio_rsp_s
#define soap_read_ns__gsmio_rsp_s(soap, data) ( ((data) ? (soap_default_ns__gsmio_rsp_s(soap, (data)), 0) : 0) || soap_begin_recv(soap) || !soap_get_ns__gsmio_rsp_s(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Reason_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Detail_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Code_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
#endif

#endif

#ifndef SOAP_TYPE_PointerTostring_DEFINED
#define SOAP_TYPE_PointerTostring_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap*, const char*, char ***, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap*, char **const*, const char*, const char*);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap*, char ***, const char*, const char*);
#endif

#ifndef SOAP_TYPE_PointerTons__gsmio_rsp_t_DEFINED
#define SOAP_TYPE_PointerTons__gsmio_rsp_t_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__gsmio_rsp_t(struct soap*, struct ns__gsmio_rsp_s *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__gsmio_rsp_t(struct soap*, const char *, int, struct ns__gsmio_rsp_s *const*, const char *);
SOAP_FMAC3 struct ns__gsmio_rsp_s ** SOAP_FMAC4 soap_in_PointerTons__gsmio_rsp_t(struct soap*, const char*, struct ns__gsmio_rsp_s **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__gsmio_rsp_t(struct soap*, struct ns__gsmio_rsp_s *const*, const char*, const char*);
SOAP_FMAC3 struct ns__gsmio_rsp_s ** SOAP_FMAC4 soap_get_PointerTons__gsmio_rsp_t(struct soap*, struct ns__gsmio_rsp_s **, const char*, const char*);
#endif

#ifndef SOAP_TYPE_PointerToint_DEFINED
#define SOAP_TYPE_PointerToint_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);
#endif

#ifndef SOAP_TYPE__XML_DEFINED
#define SOAP_TYPE__XML_DEFINED
#endif

#ifndef SOAP_TYPE__QName_DEFINED
#define SOAP_TYPE__QName_DEFINED

#ifdef SOAP_DEFAULT__QName
#define soap_default__QName(soap, a) (*(a) = SOAP_DEFAULT__QName)
#else
#define soap_default__QName(soap, a) (*(a) = (char *)0)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);

#define soap__QName2s(soap, a) soap_QName2s(soap, (a))
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);

#define soap_s2_QName(soap, s, a) soap_s2QName((soap), (s), (char**)(a), 0, -1, NULL)
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
#define soap_new__QName soap_new_string

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || soap_put__QName(soap, data, "QName", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifndef SOAP_TYPE_string_DEFINED
#define SOAP_TYPE_string_DEFINED

#ifdef SOAP_DEFAULT_string
#define soap_default_string(soap, a) (*(a) = SOAP_DEFAULT_string)
#else
#define soap_default_string(soap, a) (*(a) = (char *)0)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);

#define soap_string2s(soap, a) (a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);

#define soap_s2string(soap, s, a) soap_s2char((soap), (s), (char**)(a), 0, -1, NULL)
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

SOAP_FMAC3 char * * SOAP_FMAC4 soap_new_string(struct soap *soap, int n);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || soap_put_string(soap, data, "string", "") || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, (data), NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

#endif

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
