/* soapServer.c
   Generated by gSOAP 2.8.36 for soap_gsmio.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.36 2016-11-29 06:42:13 GMT")
SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if ((soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap))) && soap->error && soap->error < SOAP_STOP)
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}
#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsmio-set-simcard-src"))
		return soap_serve_ns__gsmio_set_simcard_src(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsmio-get-simcard-src"))
		return soap_serve_ns__gsmio_get_simcard_src(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsmio-pwr-on"))
		return soap_serve_ns__gsmio_pwr_on(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsmio-pwr-off"))
		return soap_serve_ns__gsmio_pwr_off(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsmio-get-pwr-status"))
		return soap_serve_ns__gsmio_get_pwr_status(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsmio-pwrkey-on"))
		return soap_serve_ns__gsmio_pwrkey_on(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsmio-pwrkey-off"))
		return soap_serve_ns__gsmio_pwrkey_off(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsmio-emerg-off"))
		return soap_serve_ns__gsmio_emerg_off(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsmio-get-pwrkey-status"))
		return soap_serve_ns__gsmio_get_pwrkey_status(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsmio-get-simcard-insert-status"))
		return soap_serve_ns__gsmio_get_simcard_insert_status(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsmio-get-gsmboard-insert-status"))
		return soap_serve_ns__gsmio_get_gsmboard_insert_status(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsmio-get-mcu-version"))
		return soap_serve_ns__gsmio_get_mcu_version(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:gsmio-get-mcu-help"))
		return soap_serve_ns__gsmio_get_mcu_help(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_set_simcard_src(struct soap *soap)
{	struct ns__gsmio_set_simcard_src soap_tmp_ns__gsmio_set_simcard_src;
	struct ns__gsmio_set_simcard_srcResponse soap_tmp_ns__gsmio_set_simcard_srcResponse;
	int soap_tmp_int;
	soap_default_ns__gsmio_set_simcard_srcResponse(soap, &soap_tmp_ns__gsmio_set_simcard_srcResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__gsmio_set_simcard_srcResponse.result = &soap_tmp_int;
	soap_default_ns__gsmio_set_simcard_src(soap, &soap_tmp_ns__gsmio_set_simcard_src);
	if (!soap_get_ns__gsmio_set_simcard_src(soap, &soap_tmp_ns__gsmio_set_simcard_src, "ns:gsmio-set-simcard-src", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsmio_set_simcard_src(soap, soap_tmp_ns__gsmio_set_simcard_src.chn, soap_tmp_ns__gsmio_set_simcard_src.src, soap_tmp_ns__gsmio_set_simcard_srcResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_set_simcard_srcResponse(soap, &soap_tmp_ns__gsmio_set_simcard_srcResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_set_simcard_srcResponse(soap, &soap_tmp_ns__gsmio_set_simcard_srcResponse, "ns:gsmio-set-simcard-srcResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_set_simcard_srcResponse(soap, &soap_tmp_ns__gsmio_set_simcard_srcResponse, "ns:gsmio-set-simcard-srcResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_get_simcard_src(struct soap *soap)
{	struct ns__gsmio_get_simcard_src soap_tmp_ns__gsmio_get_simcard_src;
	struct ns__gsmio_rsp_s result;
	soap_default_ns__gsmio_rsp_t(soap, &result);
	soap_default_ns__gsmio_get_simcard_src(soap, &soap_tmp_ns__gsmio_get_simcard_src);
	if (!soap_get_ns__gsmio_get_simcard_src(soap, &soap_tmp_ns__gsmio_get_simcard_src, "ns:gsmio-get-simcard-src", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsmio_get_simcard_src(soap, soap_tmp_ns__gsmio_get_simcard_src.chn, &result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_rsp_t(soap, &result);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_rsp_t(soap, &result, "ns:gsmio-rsp-t", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_rsp_t(soap, &result, "ns:gsmio-rsp-t", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_pwr_on(struct soap *soap)
{	struct ns__gsmio_pwr_on soap_tmp_ns__gsmio_pwr_on;
	struct ns__gsmio_pwr_onResponse soap_tmp_ns__gsmio_pwr_onResponse;
	int soap_tmp_int;
	soap_default_ns__gsmio_pwr_onResponse(soap, &soap_tmp_ns__gsmio_pwr_onResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__gsmio_pwr_onResponse.result = &soap_tmp_int;
	soap_default_ns__gsmio_pwr_on(soap, &soap_tmp_ns__gsmio_pwr_on);
	if (!soap_get_ns__gsmio_pwr_on(soap, &soap_tmp_ns__gsmio_pwr_on, "ns:gsmio-pwr-on", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsmio_pwr_on(soap, soap_tmp_ns__gsmio_pwr_on.chn, soap_tmp_ns__gsmio_pwr_onResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_pwr_onResponse(soap, &soap_tmp_ns__gsmio_pwr_onResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_pwr_onResponse(soap, &soap_tmp_ns__gsmio_pwr_onResponse, "ns:gsmio-pwr-onResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_pwr_onResponse(soap, &soap_tmp_ns__gsmio_pwr_onResponse, "ns:gsmio-pwr-onResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_pwr_off(struct soap *soap)
{	struct ns__gsmio_pwr_off soap_tmp_ns__gsmio_pwr_off;
	struct ns__gsmio_pwr_offResponse soap_tmp_ns__gsmio_pwr_offResponse;
	int soap_tmp_int;
	soap_default_ns__gsmio_pwr_offResponse(soap, &soap_tmp_ns__gsmio_pwr_offResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__gsmio_pwr_offResponse.result = &soap_tmp_int;
	soap_default_ns__gsmio_pwr_off(soap, &soap_tmp_ns__gsmio_pwr_off);
	if (!soap_get_ns__gsmio_pwr_off(soap, &soap_tmp_ns__gsmio_pwr_off, "ns:gsmio-pwr-off", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsmio_pwr_off(soap, soap_tmp_ns__gsmio_pwr_off.chn, soap_tmp_ns__gsmio_pwr_offResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_pwr_offResponse(soap, &soap_tmp_ns__gsmio_pwr_offResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_pwr_offResponse(soap, &soap_tmp_ns__gsmio_pwr_offResponse, "ns:gsmio-pwr-offResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_pwr_offResponse(soap, &soap_tmp_ns__gsmio_pwr_offResponse, "ns:gsmio-pwr-offResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_get_pwr_status(struct soap *soap)
{	struct ns__gsmio_get_pwr_status soap_tmp_ns__gsmio_get_pwr_status;
	struct ns__gsmio_rsp_s result;
	soap_default_ns__gsmio_rsp_t(soap, &result);
	soap_default_ns__gsmio_get_pwr_status(soap, &soap_tmp_ns__gsmio_get_pwr_status);
	if (!soap_get_ns__gsmio_get_pwr_status(soap, &soap_tmp_ns__gsmio_get_pwr_status, "ns:gsmio-get-pwr-status", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsmio_get_pwr_status(soap, soap_tmp_ns__gsmio_get_pwr_status.chn, &result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_rsp_t(soap, &result);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_rsp_t(soap, &result, "ns:gsmio-rsp-t", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_rsp_t(soap, &result, "ns:gsmio-rsp-t", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_pwrkey_on(struct soap *soap)
{	struct ns__gsmio_pwrkey_on soap_tmp_ns__gsmio_pwrkey_on;
	struct ns__gsmio_pwrkey_onResponse soap_tmp_ns__gsmio_pwrkey_onResponse;
	int soap_tmp_int;
	soap_default_ns__gsmio_pwrkey_onResponse(soap, &soap_tmp_ns__gsmio_pwrkey_onResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__gsmio_pwrkey_onResponse.result = &soap_tmp_int;
	soap_default_ns__gsmio_pwrkey_on(soap, &soap_tmp_ns__gsmio_pwrkey_on);
	if (!soap_get_ns__gsmio_pwrkey_on(soap, &soap_tmp_ns__gsmio_pwrkey_on, "ns:gsmio-pwrkey-on", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsmio_pwrkey_on(soap, soap_tmp_ns__gsmio_pwrkey_on.chn, soap_tmp_ns__gsmio_pwrkey_onResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_pwrkey_onResponse(soap, &soap_tmp_ns__gsmio_pwrkey_onResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_pwrkey_onResponse(soap, &soap_tmp_ns__gsmio_pwrkey_onResponse, "ns:gsmio-pwrkey-onResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_pwrkey_onResponse(soap, &soap_tmp_ns__gsmio_pwrkey_onResponse, "ns:gsmio-pwrkey-onResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_pwrkey_off(struct soap *soap)
{	struct ns__gsmio_pwrkey_off soap_tmp_ns__gsmio_pwrkey_off;
	struct ns__gsmio_pwrkey_offResponse soap_tmp_ns__gsmio_pwrkey_offResponse;
	int soap_tmp_int;
	soap_default_ns__gsmio_pwrkey_offResponse(soap, &soap_tmp_ns__gsmio_pwrkey_offResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__gsmio_pwrkey_offResponse.result = &soap_tmp_int;
	soap_default_ns__gsmio_pwrkey_off(soap, &soap_tmp_ns__gsmio_pwrkey_off);
	if (!soap_get_ns__gsmio_pwrkey_off(soap, &soap_tmp_ns__gsmio_pwrkey_off, "ns:gsmio-pwrkey-off", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsmio_pwrkey_off(soap, soap_tmp_ns__gsmio_pwrkey_off.chn, soap_tmp_ns__gsmio_pwrkey_offResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_pwrkey_offResponse(soap, &soap_tmp_ns__gsmio_pwrkey_offResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_pwrkey_offResponse(soap, &soap_tmp_ns__gsmio_pwrkey_offResponse, "ns:gsmio-pwrkey-offResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_pwrkey_offResponse(soap, &soap_tmp_ns__gsmio_pwrkey_offResponse, "ns:gsmio-pwrkey-offResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_emerg_off(struct soap *soap)
{	struct ns__gsmio_emerg_off soap_tmp_ns__gsmio_emerg_off;
	struct ns__gsmio_emerg_offResponse soap_tmp_ns__gsmio_emerg_offResponse;
	int soap_tmp_int;
	soap_default_ns__gsmio_emerg_offResponse(soap, &soap_tmp_ns__gsmio_emerg_offResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ns__gsmio_emerg_offResponse.result = &soap_tmp_int;
	soap_default_ns__gsmio_emerg_off(soap, &soap_tmp_ns__gsmio_emerg_off);
	if (!soap_get_ns__gsmio_emerg_off(soap, &soap_tmp_ns__gsmio_emerg_off, "ns:gsmio-emerg-off", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsmio_emerg_off(soap, soap_tmp_ns__gsmio_emerg_off.chn, soap_tmp_ns__gsmio_emerg_offResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_emerg_offResponse(soap, &soap_tmp_ns__gsmio_emerg_offResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_emerg_offResponse(soap, &soap_tmp_ns__gsmio_emerg_offResponse, "ns:gsmio-emerg-offResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_emerg_offResponse(soap, &soap_tmp_ns__gsmio_emerg_offResponse, "ns:gsmio-emerg-offResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_get_pwrkey_status(struct soap *soap)
{	struct ns__gsmio_get_pwrkey_status soap_tmp_ns__gsmio_get_pwrkey_status;
	struct ns__gsmio_rsp_s result;
	soap_default_ns__gsmio_rsp_t(soap, &result);
	soap_default_ns__gsmio_get_pwrkey_status(soap, &soap_tmp_ns__gsmio_get_pwrkey_status);
	if (!soap_get_ns__gsmio_get_pwrkey_status(soap, &soap_tmp_ns__gsmio_get_pwrkey_status, "ns:gsmio-get-pwrkey-status", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsmio_get_pwrkey_status(soap, soap_tmp_ns__gsmio_get_pwrkey_status.chn, &result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_rsp_t(soap, &result);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_rsp_t(soap, &result, "ns:gsmio-rsp-t", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_rsp_t(soap, &result, "ns:gsmio-rsp-t", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_get_simcard_insert_status(struct soap *soap)
{	struct ns__gsmio_get_simcard_insert_status soap_tmp_ns__gsmio_get_simcard_insert_status;
	struct ns__gsmio_rsp_s result;
	soap_default_ns__gsmio_rsp_t(soap, &result);
	soap_default_ns__gsmio_get_simcard_insert_status(soap, &soap_tmp_ns__gsmio_get_simcard_insert_status);
	if (!soap_get_ns__gsmio_get_simcard_insert_status(soap, &soap_tmp_ns__gsmio_get_simcard_insert_status, "ns:gsmio-get-simcard-insert-status", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsmio_get_simcard_insert_status(soap, soap_tmp_ns__gsmio_get_simcard_insert_status.chn, &result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_rsp_t(soap, &result);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_rsp_t(soap, &result, "ns:gsmio-rsp-t", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_rsp_t(soap, &result, "ns:gsmio-rsp-t", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_get_gsmboard_insert_status(struct soap *soap)
{	struct ns__gsmio_get_gsmboard_insert_status soap_tmp_ns__gsmio_get_gsmboard_insert_status;
	struct ns__gsmio_rsp_s result;
	soap_default_ns__gsmio_rsp_t(soap, &result);
	soap_default_ns__gsmio_get_gsmboard_insert_status(soap, &soap_tmp_ns__gsmio_get_gsmboard_insert_status);
	if (!soap_get_ns__gsmio_get_gsmboard_insert_status(soap, &soap_tmp_ns__gsmio_get_gsmboard_insert_status, "ns:gsmio-get-gsmboard-insert-status", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsmio_get_gsmboard_insert_status(soap, soap_tmp_ns__gsmio_get_gsmboard_insert_status.chn, &result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_rsp_t(soap, &result);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_rsp_t(soap, &result, "ns:gsmio-rsp-t", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_rsp_t(soap, &result, "ns:gsmio-rsp-t", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_get_mcu_version(struct soap *soap)
{	struct ns__gsmio_get_mcu_version soap_tmp_ns__gsmio_get_mcu_version;
	struct ns__gsmio_get_mcu_versionResponse soap_tmp_ns__gsmio_get_mcu_versionResponse;
	char * soap_tmp_string;
	soap_default_ns__gsmio_get_mcu_versionResponse(soap, &soap_tmp_ns__gsmio_get_mcu_versionResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__gsmio_get_mcu_versionResponse.result = &soap_tmp_string;
	soap_default_ns__gsmio_get_mcu_version(soap, &soap_tmp_ns__gsmio_get_mcu_version);
	if (!soap_get_ns__gsmio_get_mcu_version(soap, &soap_tmp_ns__gsmio_get_mcu_version, "ns:gsmio-get-mcu-version", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsmio_get_mcu_version(soap, soap_tmp_ns__gsmio_get_mcu_versionResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_get_mcu_versionResponse(soap, &soap_tmp_ns__gsmio_get_mcu_versionResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_get_mcu_versionResponse(soap, &soap_tmp_ns__gsmio_get_mcu_versionResponse, "ns:gsmio-get-mcu-versionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_get_mcu_versionResponse(soap, &soap_tmp_ns__gsmio_get_mcu_versionResponse, "ns:gsmio-get-mcu-versionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__gsmio_get_mcu_help(struct soap *soap)
{	struct ns__gsmio_get_mcu_help soap_tmp_ns__gsmio_get_mcu_help;
	struct ns__gsmio_get_mcu_helpResponse soap_tmp_ns__gsmio_get_mcu_helpResponse;
	char * soap_tmp_string;
	soap_default_ns__gsmio_get_mcu_helpResponse(soap, &soap_tmp_ns__gsmio_get_mcu_helpResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__gsmio_get_mcu_helpResponse.result = &soap_tmp_string;
	soap_default_ns__gsmio_get_mcu_help(soap, &soap_tmp_ns__gsmio_get_mcu_help);
	if (!soap_get_ns__gsmio_get_mcu_help(soap, &soap_tmp_ns__gsmio_get_mcu_help, "ns:gsmio-get-mcu-help", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__gsmio_get_mcu_help(soap, soap_tmp_ns__gsmio_get_mcu_helpResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_get_mcu_helpResponse(soap, &soap_tmp_ns__gsmio_get_mcu_helpResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_get_mcu_helpResponse(soap, &soap_tmp_ns__gsmio_get_mcu_helpResponse, "ns:gsmio-get-mcu-helpResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_get_mcu_helpResponse(soap, &soap_tmp_ns__gsmio_get_mcu_helpResponse, "ns:gsmio-get-mcu-helpResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
