/* soapClient.c
   Generated by gSOAP 2.8.36 for soap_gsmio.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.36 2016-11-29 06:42:13 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_set_simcard_src(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, int src, int *result)
{	struct ns__gsmio_set_simcard_src soap_tmp_ns__gsmio_set_simcard_src;
	struct ns__gsmio_set_simcard_srcResponse *soap_tmp_ns__gsmio_set_simcard_srcResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websrv.cs.fsu.edu/~engelen/calcserver.cgi";
	soap_tmp_ns__gsmio_set_simcard_src.chn = chn;
	soap_tmp_ns__gsmio_set_simcard_src.src = src;
	soap_begin(soap);
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_set_simcard_src(soap, &soap_tmp_ns__gsmio_set_simcard_src);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_set_simcard_src(soap, &soap_tmp_ns__gsmio_set_simcard_src, "ns:gsmio-set-simcard-src", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_set_simcard_src(soap, &soap_tmp_ns__gsmio_set_simcard_src, "ns:gsmio-set-simcard-src", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_int(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns__gsmio_set_simcard_srcResponse = soap_get_ns__gsmio_set_simcard_srcResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns__gsmio_set_simcard_srcResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ns__gsmio_set_simcard_srcResponse->result)
		*result = *soap_tmp_ns__gsmio_set_simcard_srcResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_get_simcard_src(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, struct ns__gsmio_rsp_s *result)
{	struct ns__gsmio_get_simcard_src soap_tmp_ns__gsmio_get_simcard_src;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websrv.cs.fsu.edu/~engelen/calcserver.cgi";
	soap_tmp_ns__gsmio_get_simcard_src.chn = chn;
	soap_begin(soap);
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_get_simcard_src(soap, &soap_tmp_ns__gsmio_get_simcard_src);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_get_simcard_src(soap, &soap_tmp_ns__gsmio_get_simcard_src, "ns:gsmio-get-simcard-src", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_get_simcard_src(soap, &soap_tmp_ns__gsmio_get_simcard_src, "ns:gsmio-get-simcard-src", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_ns__gsmio_rsp_t(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns__gsmio_rsp_t(soap, result, "", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_pwr_on(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, int *result)
{	struct ns__gsmio_pwr_on soap_tmp_ns__gsmio_pwr_on;
	struct ns__gsmio_pwr_onResponse *soap_tmp_ns__gsmio_pwr_onResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websrv.cs.fsu.edu/~engelen/calcserver.cgi";
	soap_tmp_ns__gsmio_pwr_on.chn = chn;
	soap_begin(soap);
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_pwr_on(soap, &soap_tmp_ns__gsmio_pwr_on);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_pwr_on(soap, &soap_tmp_ns__gsmio_pwr_on, "ns:gsmio-pwr-on", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_pwr_on(soap, &soap_tmp_ns__gsmio_pwr_on, "ns:gsmio-pwr-on", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_int(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns__gsmio_pwr_onResponse = soap_get_ns__gsmio_pwr_onResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns__gsmio_pwr_onResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ns__gsmio_pwr_onResponse->result)
		*result = *soap_tmp_ns__gsmio_pwr_onResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_pwr_off(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, int *result)
{	struct ns__gsmio_pwr_off soap_tmp_ns__gsmio_pwr_off;
	struct ns__gsmio_pwr_offResponse *soap_tmp_ns__gsmio_pwr_offResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websrv.cs.fsu.edu/~engelen/calcserver.cgi";
	soap_tmp_ns__gsmio_pwr_off.chn = chn;
	soap_begin(soap);
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_pwr_off(soap, &soap_tmp_ns__gsmio_pwr_off);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_pwr_off(soap, &soap_tmp_ns__gsmio_pwr_off, "ns:gsmio-pwr-off", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_pwr_off(soap, &soap_tmp_ns__gsmio_pwr_off, "ns:gsmio-pwr-off", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_int(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns__gsmio_pwr_offResponse = soap_get_ns__gsmio_pwr_offResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns__gsmio_pwr_offResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ns__gsmio_pwr_offResponse->result)
		*result = *soap_tmp_ns__gsmio_pwr_offResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_get_pwr_status(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, struct ns__gsmio_rsp_s *result)
{	struct ns__gsmio_get_pwr_status soap_tmp_ns__gsmio_get_pwr_status;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websrv.cs.fsu.edu/~engelen/calcserver.cgi";
	soap_tmp_ns__gsmio_get_pwr_status.chn = chn;
	soap_begin(soap);
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_get_pwr_status(soap, &soap_tmp_ns__gsmio_get_pwr_status);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_get_pwr_status(soap, &soap_tmp_ns__gsmio_get_pwr_status, "ns:gsmio-get-pwr-status", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_get_pwr_status(soap, &soap_tmp_ns__gsmio_get_pwr_status, "ns:gsmio-get-pwr-status", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_ns__gsmio_rsp_t(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns__gsmio_rsp_t(soap, result, "", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_pwrkey_on(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, int *result)
{	struct ns__gsmio_pwrkey_on soap_tmp_ns__gsmio_pwrkey_on;
	struct ns__gsmio_pwrkey_onResponse *soap_tmp_ns__gsmio_pwrkey_onResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websrv.cs.fsu.edu/~engelen/calcserver.cgi";
	soap_tmp_ns__gsmio_pwrkey_on.chn = chn;
	soap_begin(soap);
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_pwrkey_on(soap, &soap_tmp_ns__gsmio_pwrkey_on);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_pwrkey_on(soap, &soap_tmp_ns__gsmio_pwrkey_on, "ns:gsmio-pwrkey-on", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_pwrkey_on(soap, &soap_tmp_ns__gsmio_pwrkey_on, "ns:gsmio-pwrkey-on", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_int(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns__gsmio_pwrkey_onResponse = soap_get_ns__gsmio_pwrkey_onResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns__gsmio_pwrkey_onResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ns__gsmio_pwrkey_onResponse->result)
		*result = *soap_tmp_ns__gsmio_pwrkey_onResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_pwrkey_off(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, int *result)
{	struct ns__gsmio_pwrkey_off soap_tmp_ns__gsmio_pwrkey_off;
	struct ns__gsmio_pwrkey_offResponse *soap_tmp_ns__gsmio_pwrkey_offResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websrv.cs.fsu.edu/~engelen/calcserver.cgi";
	soap_tmp_ns__gsmio_pwrkey_off.chn = chn;
	soap_begin(soap);
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_pwrkey_off(soap, &soap_tmp_ns__gsmio_pwrkey_off);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_pwrkey_off(soap, &soap_tmp_ns__gsmio_pwrkey_off, "ns:gsmio-pwrkey-off", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_pwrkey_off(soap, &soap_tmp_ns__gsmio_pwrkey_off, "ns:gsmio-pwrkey-off", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_int(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns__gsmio_pwrkey_offResponse = soap_get_ns__gsmio_pwrkey_offResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns__gsmio_pwrkey_offResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ns__gsmio_pwrkey_offResponse->result)
		*result = *soap_tmp_ns__gsmio_pwrkey_offResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_emerg_off(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, int *result)
{	struct ns__gsmio_emerg_off soap_tmp_ns__gsmio_emerg_off;
	struct ns__gsmio_emerg_offResponse *soap_tmp_ns__gsmio_emerg_offResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websrv.cs.fsu.edu/~engelen/calcserver.cgi";
	soap_tmp_ns__gsmio_emerg_off.chn = chn;
	soap_begin(soap);
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_emerg_off(soap, &soap_tmp_ns__gsmio_emerg_off);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_emerg_off(soap, &soap_tmp_ns__gsmio_emerg_off, "ns:gsmio-emerg-off", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_emerg_off(soap, &soap_tmp_ns__gsmio_emerg_off, "ns:gsmio-emerg-off", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_int(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns__gsmio_emerg_offResponse = soap_get_ns__gsmio_emerg_offResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns__gsmio_emerg_offResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ns__gsmio_emerg_offResponse->result)
		*result = *soap_tmp_ns__gsmio_emerg_offResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_get_pwrkey_status(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, struct ns__gsmio_rsp_s *result)
{	struct ns__gsmio_get_pwrkey_status soap_tmp_ns__gsmio_get_pwrkey_status;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websrv.cs.fsu.edu/~engelen/calcserver.cgi";
	soap_tmp_ns__gsmio_get_pwrkey_status.chn = chn;
	soap_begin(soap);
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_get_pwrkey_status(soap, &soap_tmp_ns__gsmio_get_pwrkey_status);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_get_pwrkey_status(soap, &soap_tmp_ns__gsmio_get_pwrkey_status, "ns:gsmio-get-pwrkey-status", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_get_pwrkey_status(soap, &soap_tmp_ns__gsmio_get_pwrkey_status, "ns:gsmio-get-pwrkey-status", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_ns__gsmio_rsp_t(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns__gsmio_rsp_t(soap, result, "", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_get_simcard_insert_status(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, struct ns__gsmio_rsp_s *result)
{	struct ns__gsmio_get_simcard_insert_status soap_tmp_ns__gsmio_get_simcard_insert_status;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websrv.cs.fsu.edu/~engelen/calcserver.cgi";
	soap_tmp_ns__gsmio_get_simcard_insert_status.chn = chn;
	soap_begin(soap);
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_get_simcard_insert_status(soap, &soap_tmp_ns__gsmio_get_simcard_insert_status);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_get_simcard_insert_status(soap, &soap_tmp_ns__gsmio_get_simcard_insert_status, "ns:gsmio-get-simcard-insert-status", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_get_simcard_insert_status(soap, &soap_tmp_ns__gsmio_get_simcard_insert_status, "ns:gsmio-get-simcard-insert-status", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_ns__gsmio_rsp_t(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns__gsmio_rsp_t(soap, result, "", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_get_gsmboard_insert_status(struct soap *soap, const char *soap_endpoint, const char *soap_action, int chn, struct ns__gsmio_rsp_s *result)
{	struct ns__gsmio_get_gsmboard_insert_status soap_tmp_ns__gsmio_get_gsmboard_insert_status;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websrv.cs.fsu.edu/~engelen/calcserver.cgi";
	soap_tmp_ns__gsmio_get_gsmboard_insert_status.chn = chn;
	soap_begin(soap);
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_get_gsmboard_insert_status(soap, &soap_tmp_ns__gsmio_get_gsmboard_insert_status);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_get_gsmboard_insert_status(soap, &soap_tmp_ns__gsmio_get_gsmboard_insert_status, "ns:gsmio-get-gsmboard-insert-status", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_get_gsmboard_insert_status(soap, &soap_tmp_ns__gsmio_get_gsmboard_insert_status, "ns:gsmio-get-gsmboard-insert-status", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_ns__gsmio_rsp_t(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns__gsmio_rsp_t(soap, result, "", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_get_mcu_version(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **result)
{	struct ns__gsmio_get_mcu_version soap_tmp_ns__gsmio_get_mcu_version;
	struct ns__gsmio_get_mcu_versionResponse *soap_tmp_ns__gsmio_get_mcu_versionResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websrv.cs.fsu.edu/~engelen/calcserver.cgi";
	soap_begin(soap);
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_get_mcu_version(soap, &soap_tmp_ns__gsmio_get_mcu_version);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_get_mcu_version(soap, &soap_tmp_ns__gsmio_get_mcu_version, "ns:gsmio-get-mcu-version", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_get_mcu_version(soap, &soap_tmp_ns__gsmio_get_mcu_version, "ns:gsmio-get-mcu-version", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	*result = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns__gsmio_get_mcu_versionResponse = soap_get_ns__gsmio_get_mcu_versionResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns__gsmio_get_mcu_versionResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ns__gsmio_get_mcu_versionResponse->result)
		*result = *soap_tmp_ns__gsmio_get_mcu_versionResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__gsmio_get_mcu_help(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **result)
{	struct ns__gsmio_get_mcu_help soap_tmp_ns__gsmio_get_mcu_help;
	struct ns__gsmio_get_mcu_helpResponse *soap_tmp_ns__gsmio_get_mcu_helpResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://websrv.cs.fsu.edu/~engelen/calcserver.cgi";
	soap_begin(soap);
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__gsmio_get_mcu_help(soap, &soap_tmp_ns__gsmio_get_mcu_help);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__gsmio_get_mcu_help(soap, &soap_tmp_ns__gsmio_get_mcu_help, "ns:gsmio-get-mcu-help", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__gsmio_get_mcu_help(soap, &soap_tmp_ns__gsmio_get_mcu_help, "ns:gsmio-get-mcu-help", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	*result = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns__gsmio_get_mcu_helpResponse = soap_get_ns__gsmio_get_mcu_helpResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns__gsmio_get_mcu_helpResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ns__gsmio_get_mcu_helpResponse->result)
		*result = *soap_tmp_ns__gsmio_get_mcu_helpResponse->result;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
